- cloudify/amqp_client.py
- cloudify/dispatch.py
- cloudify/logs.py
- cloudify/tests/test_dispatch.py
Logs from subprocesses are sent to the main process via stdout, and
only the main process writes to the file
> CY-336 Multiprocess logging

- cloudify/amqp_client.py
- cloudify/constants.py
- cloudify/dispatch.py
- cloudify/logs.py
- cloudify/utils.py
- cloudify/workflows/workflow_context.py
* Add a hook publisher so the hooks will be published with
events.hooks routing key
* Events will be published with events routing key
> CY-540 Create hook mechanism

- cloudify/dispatch.py
- cloudify/logs.py
- cloudify/tests/mocks/mock_module.py
* Add mock function for hooks integration tests
* Add execution_parameters to WorkflowHandler because kwargs is being updated with
the context
* Add tenant_name to the event message context
* Add the is_system_workflow and execution_parameters to the message context
of an actionable events (hooks)
> CY-540 Add mock function for hooks integration tests

- MANIFEST.in
- cloudify/snmp/CLOUDIFY-MIB.mib
- cloudify/snmp/snmp_trap.py
* Rename the type cloudifyWorkflowCompleted to cloudifyWorkflowSucceeded in our mib
* Remove the revisions from our mib file, it wasn't published yet
* Make sure the CLOUDIFY-MIB.mib file will be part of the snmp package
> CY-542 Rename the type cloudifyWorkflowCompleted to cloudifyWorkflowSucceeded in our mib

- cloudify_rest_client/utils.py
> Only add o+r

- cloudify/constants.py
- cloudify/cryptography_utils.py
This way it can be used easily during snapshot restore
> Move cryptography_utils to cloudify-common

- script_runner/tasks.py
- script_runner/tests/__init__.py
- script_runner/tests/test_ctx_wrapper.py
- script_runner/tests/test_script_runner.py
To do this, I restored much of the code from script plugin 1.5.1.
> CY-781: stdout/stderr printed to ctx logger by default

- cloudify/manager.py
* When an agent is being deleted (like in uninstall) it stays in the DB
with the state `deleted`
* In reinstall we create the agent again and because it's already in the DB
we only change its state
> CY-764 In case of reinstalling the agent, update its state

- cloudify/amqp_client.py
No need for the default after all
> CY-780 amqp_client: use the heartbeat value from broker_config

- cloudify/workflows/tasks_graph.py
Every execute call can throw its own error :)
> TasksGraph: clear current error on every execute call

- dsl_parser/constants.py
- dsl_parser/elements/blueprint.py
- dsl_parser/elements/imports.py
- dsl_parser/elements/misc.py
- dsl_parser/parser.py
- dsl_parser/tests/test_blueprint_import.py
- dsl_parser/tests/test_cloudify_basic_types_mark.py
- dsl_parser/tests/test_parser_api.py
- dsl_parser/utils.py
- The imported list will contain only blueprint imports, due that there is only a need for them
- Now the imported list will come also from the imported blueprints, if local or blueprint imports
> CY-642: improving blueprint imported list

- dsl_parser/functions.py
- dsl_parser/tests/test_get_capability.py
- This makes it behave similarly to get_attribute.
- Preserves old behavior.
> CY-866 Add ability to get_capability to get nested property

- dsl_parser/elements/operation.py
- dsl_parser/framework/elements.py
- dsl_parser/framework/parser.py
- dsl_parser/parser.py
- dsl_parser/tests/test_cloudify_basic_types_mark.py
- dsl_parser/utils.py
- Adding support for blueprint import with namespace inside
- fixing prevention of namespace on Cloudify basic types
> CY-642 : import namespace support

- dsl_parser/exceptions.py
- dsl_parser/functions.py
- dsl_parser/scan.py
- dsl_parser/tests/test_functions.py
- dsl_parser/tests/test_get_capability.py
- dsl_parser/tests/test_register_function.py
Adds the ability to call other intrinsic functions within intrinsic functions.
> CY-884 Add support for nested intrinsic function calls

- dsl_parser/elements/imports.py
- dsl_parser/tests/test_blueprint_import.py
Adding protection for multi import with local cloudify basic types
> CY-642: import with local cloudify basic types

- cloudify/workflows/workflow_context.py
* Add kwargs to the store_operation method
* Change operation_name param to name
> Fix, add kwargs to the store_operation method

- dsl_parser/elements/imports.py
- dsl_parser/framework/parser.py
- dsl_parser/holder.py
- dsl_parser/tests/abstract_test_parser.py
- dsl_parser/tests/test_relationships_overloading.py
- dsl_parser/utils.py
* node templates relationships overloading support
* General refactors to namespacing process
> CY-962 : node templates relationships overloading

- dsl_parser/holder.py
And removed weird `in fact` usage
> Corrected typo

- dsl_parser/elements/imports.py
- dsl_parser/tests/namespace/test_general_namespace.py
fixing namespace collision in case of same namespace for the same depth import or in one deeper level
> CY-1050: fixing namespace collision

- cloudify/plugins/lifecycle.py
- cloudify/tests/resources/blueprints/test-lifecycle.yaml
- cloudify/tests/test_builtin_workflows.py
Added: `precreate`, `poststart`, `prestop`, `postdelete`.
> CY-1175: additional lifecycle operations

- cloudify/dispatch.py
- cloudify/logs.py
* Use OperationHandler as the hook task handler
* Don't send the the ctx to the hook implementaion
* Change the tenant_name of the event message to tenant object
> CY-1041 Refactor the actionable events (hooks)

- cloudify/dispatch.py
- cloudify/workflows/workflow_context.py
> Running an execution already in started state is a resume

- .circleci/config.yml
> py26 build fix

- cloudify/tests/test_proxy.py
- cloudify/tests/test_task_serialize.py
- cloudify/tests/test_tasks_graph.py
- cloudify/tests/test_utils.py
- cloudify/workflows/tasks.py
- dsl_parser/constraints.py
- dsl_parser/elements/imports.py
- dsl_parser/elements/inputs.py
- dsl_parser/elements/node_types.py
- dsl_parser/functions.py
- dsl_parser/tests/test_inputs.py
Makes me cry to do this, and yet here we go
> Back to 2.6-friendly syntax

- cloudify/manager.py
Instead of throwing a NonRecoverable right there while trying the
deployment path, actually do try all the paths
> get_resource: continue to blueprint, if deployment resource is 404

- cloudify/amqp_client.py
When client.add_handler is called after the connection has
already been made, the register function was called in the
calling thread, not in the connection thread.
This made it so that we were avoiding that mode of .add_handler
(always calling it before connecting instead), because the alternative
was unsecured multithreaded access to the connection.
With this change, register is always called from the connection
thread when .add_handler is used, which makes it safe to add handlers
after the connection has already been made.
> amqp_client: call handlers' register in-thread

- cloudify/plugins/workflows.py
- cloudify/tests/test_utils.py
- cloudify/utils.py
- cloudify_rest_client/client.py
- cloudify_rest_client/deployment_updates.py
- cloudify_rest_client/plugins_update.py
- docs/cloudify_rest_client/deployment_updates.rst
- docs/cloudify_rest_client/plugins_updates.rst
- Adds an update_plugins flag to the deployment update API calls
> CY-1060 Add the plugins update API to client

- cloudify/plugins/install_utils.py
- cloudify_rest_client/plugins.py
> New command to remove the 'installing' prefix from

- cloudify/amqp_client.py
This is because other amqp users are only allowed to access queues
named like that, note in https://github.com/cloudify-cosmo/cloudify-manager/blob/master/rest-service/manager_rest/amqp_manager.py#L198
> RequestResponse: response queue names start with response_

- cloudify/endpoint.py
Providercontext can be overridden by config
> Add workflow config to bootstrapcontext

- dsl_parser/functions.py
- dsl_parser/tests/test_capabilities.py
- The missing scope was in capabilities, but there is not real reason to restrict for all places
> CY-1558: removing any restriction on concat

- packaging/plugins/provision.sh
Reverts cloudify-cosmo/cloudify-common#351
> Revert "Update provision.sh"

- cloudify/context.py
- cloudify/dispatch.py
- cloudify/models_states.py
- cloudify/proxy/server.py
- cloudify/test_utils/__init__.py
- cloudify/test_utils/local_workflow_decorator.py
- cloudify/tests/test_builtin_workflows.py
- cloudify/tests/test_context.py
- cloudify/tests/test_local_workflows.py
- cloudify_rest_client/client.py
- docs/cloudify_dsl_parser/conf.py
- docs/cloudify_plugins_common/conf.py
- docs/cloudify_rest_client/conf.py
- docs/cloudify_script_plugin/conf.py
- dsl_parser/constraints.py
- dsl_parser/import_resolver/abstract_import_resolver.py
- dsl_parser/rel_graph.py
- dsl_parser/tests/test_deafult_import_resolver.py
- dsl_parser/tests/test_functions.py
- dsl_parser/tests/test_outputs.py
- dsl_parser/utils.py
- script_runner/tasks.py
- setup.py
Just "stage1" changes that carry no risk and are 2+3 safe.
This will allow importing some of the modules under py3, which
will allow some users to start porting their plugins to py3
> CY-1374 Basic py2+3 compat changes

- cloudify/_compat.py
- cloudify/amqp_client.py
- cloudify/amqp_client_utils.py
- cloudify/event.py
- cloudify/utils.py
- cloudify_rest_client/_compat.py
- cloudify_rest_client/blueprints.py
- cloudify_rest_client/deployment_updates.py
- cloudify_rest_client/plugins.py
- cloudify_rest_client/snapshots.py
For 2+3 compatibility.
This actually allows `import cloudify.mocks` in py3
> CY-1374 Move several imports to a compat module

- cloudify/systemddbus.py
The systemddbus would be in use by the rest-service and by the status
reporters.
> CY-1717 Move systemddbus module to common

- packaging/plugins/Vagrantfile
- packaging/plugins/provision.sh
due to that github stopped supporting auth via password
> github token - move all to use github token

- cloudify/context.py
- cloudify/dispatch.py
- cloudify/tests/test_dispatch.py
> CY-1959 Check if operation is resumable after updating state

- .circleci/py3fixers
- cloudify/snapshots.py
- dsl_parser/constraints.py
- dsl_parser/elements/__init__.py
- dsl_parser/elements/operation.py
- dsl_parser/framework/parser.py
- dsl_parser/tests/test_inputs.py
- dsl_parser/utils.py
- script_runner/tasks.py
> CY-2367 python3 porting: stage2 changes

- cloudify/_compat.py
- cloudify/workflows/local.py
Stop eating the traceback! I want to be able to debug!
> Local workflows: reraise exceptions with traceback

- .circleci/config.yml
- .circleci/py3fixers
- cloudify/ctx_wrappers/ctx-py.py
- cloudify/utils.py
- dsl_parser/_compat.py
- dsl_parser/functions.py
- dsl_parser/import_resolver/abstract_import_resolver.py
- dsl_parser/tests/scaling/__init__.py
- dsl_parser/tests/test_inputs.py
> CY-2367 Py3 porting: more stage2 changes

- .circleci/config.yml
- cloudify/_compat.py
- cloudify/ctx_wrappers/ctx-py.py
- cloudify/workflows/tasks.py
- cloudify_rest_client/_compat.py
- dsl_parser/_compat.py
- dsl_parser/utils.py
- script_runner/tests/test_script_runner.py
Now running flake8 on py3 and on py2
> CY-2411 Run flake8 on python 3

- cloudify_rest_client/blueprints.py
Add `BlueprintsClient.validate()` method in `cloudify_rest_client` module for handling blueprints validation.  As validation is quite similar to upload, there is some refactoring as well.
> CY-2363 Add a "validate blueprint" REST endpoint

- cloudify/_compat.py
- cloudify/dispatch.py
- cloudify/error_handling.py
- cloudify/proxy/client.py
- cloudify/proxy/server.py
- cloudify/rabbitmq_client.py
- cloudify/tests/_compat.py
- cloudify/tests/file_server.py
- cloudify/tests/test_local_workflows.py
- cloudify/tests/test_operation_retry.py
- cloudify/tests/test_proxy.py
- cloudify/tests/test_state.py
- cloudify/workflows/local.py
- cloudify/workflows/tasks.py
- cloudify/workflows/workflow_context.py
- cloudify_rest_client/blueprints.py
- cloudify_rest_client/deployment_updates.py
- dsl_parser/_compat.py
- dsl_parser/elements/imports.py
- dsl_parser/framework/elements.py
- dsl_parser/import_resolver/abstract_import_resolver.py
- dsl_parser/tests/abstract_test_parser.py
- dsl_parser/tests/test_parser_api.py
- dsl_parser/utils.py
Import things in _compat modules, in a py2+3 compatible way
> CY-2367 Py3 porting: import moves

- cloudify/event.py
- cloudify/exceptions.py
- cloudify/tests/test_context.py
- cloudify/tests/test_ctx_relationships.py
- cloudify/tests/test_decorators.py
- cloudify/tests/test_dispatch.py
- cloudify/tests/test_event.py
- cloudify/tests/test_local_workflows.py
- cloudify/tests/test_missing_operation.py
- cloudify/tests/test_proxy.py
- cloudify/tests/test_tasks_graph.py
- cloudify/workflows/tasks_graph.py
- dsl_parser/functions.py
- dsl_parser/tasks.py
- dsl_parser/tests/abstract_test_parser.py
- dsl_parser/tests/namespace/test_functions.py
- dsl_parser/tests/namespace/test_node_types.py
- dsl_parser/tests/namespace/test_plugins.py
- dsl_parser/tests/namespace/test_workflows.py
- dsl_parser/tests/test_data_types.py
- dsl_parser/tests/test_functions.py
- dsl_parser/tests/test_get_secret.py
- dsl_parser/tests/test_import_resolver.py
- dsl_parser/tests/test_inputs.py
- dsl_parser/tests/test_parser_api.py
- script_runner/tests/test_ctx_wrapper.py
- script_runner/tests/test_script_runner.py
Assorted random test fixes.
This isn't enough to have the tests be green yet, because
there's still some unicode/bytes changes to be done, but
this is the "random fixes" PR.
See each commit for explanation
> CY-2411 Py3 porting: test fixes

- cloudify/_compat.py
- dsl_parser/framework/elements.py
random stuff, probably much more to come
> Py3 porting: fixups

- cloudify/_compat.py
Going to be useful in a few places
> Add `exec_` to compat

- cloudify/_compat.py
- cloudify/tests/test_utils.py
- cloudify/utils.py
- script_runner/tasks.py
> Py3-compat fixups

- cloudify/_compat.py
> _compat.py: add urlencode and unquote

- cloudify/plugins/lifecycle.py
also re-load the locally referenced sets
> reinstall_node_instances: refresh the node instances

- cloudify/plugins/workflows.py
- cloudify/workflows/workflow_context.py
This is a port of #483 to 5.0.5.
See the original PR for comments and explanation.
> CY-2900 Refresh node instances

- cloudify/dispatch.py
worker_installer is the 3.2 compat agent installer
> Add worker_installer to preinstalled plugins

- cloudify/agent_utils.py
- cloudify/rabbitmq_client.py
This is to be used when deleting the agent
> CY-3216 Add methods to delete agent queues and exchange

- cloudify/dispatch.py
Those things are not required for anything
> Remove useless cruft from dispatch.py

- cloudify/workflows/workflow_context.py
- cloudify_rest_client/operations.py
Follow through pagination. Simple as that.
> CY-3419 get_operations: fetch all operations

- cloudify/workflows/tasks.py
I used this while debugging and it was more useful than before.
> More useful reprs for workflow tasks

- cloudify/tests/test_utils.py
- jenkins/Jenkinsfile
- jenkins/build-pod.yaml
Creating Jenkinsfile and pod-yaml file for new EKS Jenkins
modifying test_utils.py
> Cy 3098 jenkinsfile

- cloudify_rest_client/client.py
for back-compat, when using the new CLI with old managers
> Still allow 200 responses in DELETE

- cloudify/agent_utils.py
similar to the restservice side, also calling from here, fetch
the rabbitmq node details and try all of them
> CY-3615 agent_utils: try all rabbitmq nodes

- cloudify/tests/resources/blueprints/execute_operation-blueprint.yaml
- cloudify/tests/resources/blueprints/install-new-agents-blueprint.yaml
- cloudify/tests/resources/blueprints/not_exist_op_workflow-blueprint.yaml
- cloudify/tests/resources/blueprints/test-blueprint-ignore-failure.yaml
- cloudify/tests/resources/blueprints/test-heal-correct-order-blueprint.yaml
- cloudify/tests/resources/blueprints/test-lifecycle-retry-blueprint.yaml
- cloudify/tests/resources/blueprints/test-relationship-order-blueprint.yaml
- cloudify/tests/resources/blueprints/test-subgraph-blueprint.yaml
- cloudify/tests/resources/blueprints/test-uninstall-ignore-failure-parameter-blueprint.yaml
- packaging/plugins/provision.sh
- setup.py
This reverts commit 76d3185b32c8266025eda584cfcd235e4c2991bc.
> Revert "Bump version"

- cloudify/cluster.py
I've had enough of the 'No active node in cluster'.
Stop hiding the underlying errors.
> CY-3685 ClusterHTTPClient: show underlying error

- cloudify/plugins/lifecycle.py
- cloudify/tests/test_task_serialize.py
- cloudify/workflows/tasks.py
- cloudify/workflows/tasks_graph.py
Commit 1 introduces the infra for serializing/deserializing them, and commit 2
implements that for builtin cases
> RD-406 Support for storing .on_failure/.on_success handlers

- cloudify_rest_client/client.py
- cloudify_rest_client/deployments.py
- cloudify_rest_client/labels.py
Adding the `/labels` endpoint mechanism to the rest-client.
> RD-484 Add labels to rest client

- cloudify_rest_client/manager.py
> RD-759 Drop `cfy ssl`

- cloudify_rest_client/client.py
- cloudify_rest_client/filters.py
Implement the filters endpoint in the rest-client.
> RD-702 Filters rest-client

- cloudify_rest_client/filters.py
Adding `get`, `delete` and `update` to filters
> RD-695 Add more commands to filters

- cloudify_rest_client/deployments.py
- cloudify_rest_client/utils.py
Adding filter rules to deployments list in the rest-client.
> RD-694 Filters in deployments list

- cloudify_rest_client/client.py
- cloudify_rest_client/deployments.py
the other part to cloudify-cosmo/cloudify-manager#2570
> Basic deployment groups RESTclient

- cloudify/plugin_installer.py
> RD-1091 plugin_installer: skip setting the uninstalled state

- cloudify_rest_client/client.py
- cloudify_rest_client/executions.py
Just starting and listing so far, no polling yet
> RD-1100 Basic execution groups restclient

- cloudify_rest_client/deployment_updates.py
- cloudify_rest_client/plugins_update.py
The parameter is used to force plugin update on blueprints used (also) as components.
> RD-872 Add --force parameter for cfy plugin update

- cloudify_rest_client/deployments.py
THe 'add' and 'remove' fields.
I still kinda hate it, I would prefer a proper RFC692 JSON-Patch
format, but for now this works.
> RD-1162 Update deployment groups restclient

- cloudify/amqp_client.py
Switch the call based on which pika we're on
> RD-1287 Keep compat between pika 1.1 and 0.11

- cloudify_rest_client/executions.py
> RD-1319 Execution group: get with details

- cloudify_rest_client/executions.py
Same meaning as in a single execution
> Execution groups: add a force param

- cloudify/workflows/workflow_context.py
> RD-1333 workflow-ctx: if no deployment id, don't fetch nodes

- cloudify_rest_client/deployments.py
Adding and removing deployments based on a filter
> RD-1099 deployment groups: pass deployments via filter id

- cloudify_rest_client/blueprints.py
- cloudify_rest_client/deployments.py
- cloudify_rest_client/utils.py
Filtering the blueprints list. 
The complementary PR for the rest service is cloudify-cosmo/cloudify-manager#2682
> RD-1424 Add filter rules to blueprints list

- cloudify_rest_client/blueprints.py
The complementary PR in the rest service is https://github.com/cloudify-cosmo/cloudify-manager/pull/2692
> RD-1431 Add labels to blueprint upload

- cloudify_rest_client/blueprints.py
Minor blueprints labels fixes.
> Blueprints labels fixes

- dsl_parser/constants.py
- dsl_parser/elements/blueprint.py
- dsl_parser/scan.py
- dsl_parser/tests/test_labels.py
Change `blueprint-labels` to `blueprint_labels`.
> RD-1467 Change blueprint-labels DSL

- cloudify_rest_client/plugins_update.py
The flag is going to be passed to the underlying deployments update
flow.
> RD-1515 Add --auto-correct-types to plugins update

- cloudify_rest_client/plugins_update.py
The flag is going to be passed to the underlying deployments update
flow.
> Add --auto-correct-types to plugins update

- cloudify_rest_client/deployments.py
> dep-groups put: actually add inputs to the data

- jenkins/Jenkinsfile
Reverts cloudify-cosmo/cloudify-common#704
> Revert "Temporarily modify pyenv source repo"

- cloudify_rest_client/deployment_updates.py
- cloudify_rest_client/plugins_update.py
* pass `force` parameter
* Add `force` parameter to the deployment-updates call
> RD-872 Add --force parameter for cfy plugin update (#635)

- dsl_parser/elements/misc.py
Groups the deployment belongs to.
> RD-1164 DSL: add default_groups

- cloudify_rest_client/deployments.py
Select deployments to be added/removed by providing another group id
> RD-1196 dep-group add/remove: add deployments_from_group

- cloudify_rest_client/deployments.py
- cloudify_rest_client/exceptions.py
This PR created in order to do the following:
1. Include extra params response as part of deployment in client deployments
2. Add new exception type when deployment reference something that does not exist
> RD-1485 Update deployment client response

- cloudify/workflows/tasks_graph.py
The bug described here https://cloudifysource.atlassian.net/browse/RD-1116 occurs because dependencies of failed tasks were not handled correctly in the restore of the task graph:
Any task which had a dependency on another task that has failed, lost this dependency upon restore, resulting in a potentially-botched execution sequence. The following code retrieves the active retried task of a failed task, and creates a dependency on it where needed.
> RD-1116 Fix handling of failed tasks' dependencies

- cloudify_rest_client/deployments.py
Deleting a deployment group, with deleting all the deployments in it.
> RD-1810 Bulk deployments delete

- cloudify_rest_client/exceptions.py
Revert handling invalid csys-environment input exception
> RD-2105 Revert handling invalid csys-environment input exception

- cloudify_rest_client/deployments.py
1. Add .description
2. It's default_blueprint_id, not default_blueprint
> restclient: update DeploymentGroup attributes

- dsl_parser/elements/misc.py
- dsl_parser/scan.py
- dsl_parser/tests/test_functions.py
Add those two into deployment_settings, and also make sure
that all of deployment_settings is scanned, not just the dicts under it
(but not strings)
> RD-1276 Add display_name & id_template

- cloudify/deployment_dependencies.py
- cloudify_rest_client/deployments.py
- cloudify_rest_client/inter_deployment_dependencies.py
The body of the call is a list of inter-deployment dependencies to be
created.
> RD-2190 Add create_many POST call to inter-deployment dependencies

- cloudify/models_states.py
not cancelled. Cancelled is end_states, not in_progress_states
> ExecutionState: cancelling is in_progress

- cloudify/amqp_client.py
`json.loads` in versions earlier than 3.6 requires unicode
> RD-2278 amqp_client: decode message body

- cloudify/dispatch.py
- cloudify/tests/test_dispatch.py
> RD-2288 Remove useless retries

- cloudify_rest_client/executions.py
> RD-1419 restclient for setting targets for exec-group

- cloudify/manager.py
- cloudify/tests/test_context.py
This patch complements the previous modification to the deployment
update: https://github.com/cloudify-cosmo/cloudify-manager/pull/2977
> RD-2316 Look for the resources in update_blueprint path

- cloudify_rest_client/exceptions.py
This just adds the exception used in cloudify-common/cloudify-manager#3060
> RD-2352 rest-client exceptions: add ForbiddenWhileCancelling

- cloudify_rest_client/client.py
This allows the user to use a single session for multiple requests,
taking advantage of a keep-alive connection.
Also, this will use a single requests.Session for all calls done
by a HTTPClient.
> RD-517 rest-client: allow passing in a requests.Session

- cloudify/workflows/workflow_context.py
Instead of fetching plugin info every time we run an operation,
cache that data, so that if we have a thousand operations from the
same plugin in a given workflow, we don't fetch the plugin
a thousand times, but only once.
> RD-2588 instance.execute_operation: cache the retrieved plugin

- cloudify/tests/test_local_workflows.py
- cloudify/tests/test_task_retry_event_context.py
- cloudify/tests/test_tasks_graph.py
- cloudify/workflows/events.py
- cloudify/workflows/tasks.py
- cloudify/workflows/workflow_context.py
- cloudify_rest_client/operations.py
They will be automatically created when updating the operation
> RD-515 Don't create events for operations

- cloudify/amqp_client.py
- cloudify/endpoint.py
- cloudify/logs.py
- cloudify/workflows/events.py
- cloudify/workflows/tasks.py
- cloudify/workflows/workflow_context.py
this brings back the logs in /var/log/cloudify/mgmtworker/logs/<dep_name>.log
> Also log events/logs when emitting them

- cloudify/workflows/tasks.py
- cloudify/workflows/workflow_context.py
Instead of using LocalWorkflowTask for all the builtin tasks
(such as set-node-instance-state, send-event, etc), make them
each be a _subclass_ of WorkflowTask.
That means they're no longer tied to LocalWorkflowTask, which is
for sending actual tasks (in cfy local) as well.
Specifically, we'll be able to just skip sending the SENDING/SENT
state updates, because they're not needed for these builtin tasks.
> RD-2650 Stop using LocalTask for the builtin tasks

- cloudify/workflows/tasks.py
From two requests, down to one!
> RD-2650 Use server-side node-instance state update

- cloudify/workflows/tasks.py
Those will be inserted automatically, saving a request
> RD-2650 Don't explicitly insert workflow node events

- cloudify/workflows/workflow_context.py
And also some other small changes
> RD-519 RemoteContextHandler: use a stored rest-client

- cloudify/endpoint.py
- cloudify/manager.py
- cloudify/workflows/workflow_context.py
> RD-519 Use a stored rest-client in ManagerEndpoint

- cloudify/cryptography_utils.py
* encrypt(None) = None
* decrypt(None) = None
> RD-2687 encrypt(None) = None

- cloudify/workflows/tasks.py
Instead of using the cached node-instances, I decided to just cache
the whole method. This means we'll still run the request once, and
get the actually-correct values, but we won't run the request
ten thousand times.
> RD-516 Cache _get_agent_settings

- cloudify/workflows/tasks.py
The automatic execution on state update, only happens if we even
update the operation state, which happens only in cases where
the tasks are in a graph.
If the tasks aren't in a graph, they're not stored and not updated,
and there needs to be an explicit implementation of the task.
Unfortunate, but still possible to do.
This fixes some inte-tests, eg `integration_tests/tests/agentless_tests/test_executions.py::ExecutionsTest::test_cancel_execution `
> set-node-instance-state task: handle non-stored tasks

- cloudify/workflows/workflow_context.py
This ports #827 to 6.1.0
See the docstring of `_task_deletes_exchange` for explanation.
As always, cache invalidation is one of the Hard™ things!
We clear the whole cache because that is trivially correct: otherwise,
it'd be hard to figure out what exchange should we even remove from
the cache, because the delete task is a mgmtworker task (and so,
target = `cloudify.management`), on the `/` (not tenant) vhost - and
so, separate Handler instances. And the exchange/queue names aren't
necessarily the same as the node-instance name, because of proxied
agents.
> RD-2679 Clear the queue-bind cache when deleting agents

- cloudify/workflows/workflow_context.py
> default exception_text to None

- cloudify_rest_client/node_instances.py
This implements the client for cloudify-cosmo/cloudify-manager#3159
> RD-2746 node-instances search rest-client

- cloudify_rest_client/node_instances.py
This ports #834 to 6.1.0
* RD-2746 node-instances search rest-client
This implements the client for cloudify-cosmo/cloudify-manager#3159
* add all_tenants
Co-authored-by: Łukasz Maksymczuk <lukasz@lukasz-maksymczuk.intra.codilime.com>
> RD-2746 node-instances search rest-client (#834)

- cloudify_rest_client/deployment_updates.py
... but to not deprecate PUT method just yet.
> RD-2786 Use POST method to initiate deployment update

- cloudify/workflows/workflow_context.py
...as opposed to just relying on the process exiting to close the
connection
> RD-2914 workflow amqp dispatcher: close amqp connections

- cloudify/plugins/lifecycle.py
graph.add_dependency really wants tasks, not ids
> RD-2967 update_resumed_install: correct arg type for graph

- cloudify/amqp_client.py
This is a backport of RD-2278.
> RD-3058 Decode amqp message body

- cloudify_rest_client/nodes.py
> RD-3086 rest-client: PATCH to update nodes

- dsl_parser/tests/abstract_test_parser.py
- dsl_parser/tests/test_functions.py
- dsl_parser/tests/test_get_attribute.py
- dsl_parser/tests/test_get_attributes_dict.py
- dsl_parser/tests/test_get_attributes_list.py
- dsl_parser/tests/test_get_capability.py
- dsl_parser/tests/test_get_environment_capability.py
- dsl_parser/tests/test_get_secret.py
- dsl_parser/tests/test_labels.py
- dsl_parser/tests/test_outputs.py
- dsl_parser/tests/test_register_function.py
The underscore there is pointless as hell.
Hi @geokala
> dsl-parser tests: expose mock_evaluation_storage sans the _

- dsl_parser/tests/test_blueprint_import.py
The original test was only asserting that the keys were the same.
It's not clear from this test why the current behaviour is what it
is, but we can at least assert that it doesn't change.
> RD-3097 Correct assertions for nested ns test

- cloudify/workflows/workflow_context.py
this is better than just an IndexError
> wctx: on plugin missing, include the plugin name in the error

- cloudify_rest_client/blueprints.py
copied from https://github.com/cloudify-cosmo/cloudify-common/pull/878
> RD-3156 New `upload_execution` Blueprint property

- cloudify_rest_client/nodes.py
Deleting a node, simple as that.
> RD-3094 REST-client: nodes.delete

- cloudify_rest_client/inter_deployment_dependencies.py
... it's purpose is to update (i.e. rewrite all) inter-deployment
dependencies with new ones.
> RD-2615 Implement update_all function for IDDs

- dsl_parser/exceptions.py
- dsl_parser/functions.py
This approach uses workflow context to retrieve information about
blueprint, deployment and tenant.
> RD-3434 Implement get_sys intrinsic function

- cloudify_rest_client/agents.py
Otherwise we'll include credentials as well as a lot of what appears to be
new information (but which was always stored).
> Default agent to include old agent details

- cloudify/workflows/local.py
- cloudify/workflows/workflow_context.py
This really continues #968, but all the boilerplate for the local
side this time.
> RD-3859 Implement the dep-update-related calls for local workflows

- cloudify/__init__.py
- cloudify/amqp_client.py
- cloudify/rabbitmq_client.py
Don't require a file, allow just a string with the contents as well.
Less tempfiles is always better!
> RD-3941 Handle amqp ca cert given as the cert contents

- cloudify/tests/test_tasks_graph.py
- cloudify/workflows/tasks_graph.py
It was actually the wrong way around. A bit of refactor, too.
> RD-4003 Reverse the condition in wait_after_fail

- cloudify/plugins/workflows.py
- cloudify/tests/resources/blueprints/minimal_types.yaml
- cloudify/tests/resources/blueprints/test-check-drift.yaml
- cloudify/tests/test_builtin_workflows.py
- cloudify/tests/test_tasks_graph.py
- cloudify/workflows/local.py
- cloudify/workflows/workflow_context.py
In principle this is similar to check_status, but a bit different!
> RD-3856 Implement the check_drift workflow

- cloudify/plugins/workflows.py
There can be many relationships, so they have to be keyed by
something, and spec suggests for it to be just keyed by the other
instance's id. (other = the target or the source)
> RD-4068 Store relationship drift with other instance's id

- cloudify/workflows/workflow_context.py
- cloudify_rest_client/operations.py
This method is going to be private, not to be touched by users,
it's only useful in dep-update.
> RD-3907 Add wctx._update_operation_inputs

- cloudify/plugins/workflows.py
- cloudify/tests/test_builtin_workflows.py
> RD-4096 Update: delegate to the new workflow

- cloudify/context.py
- cloudify/workflows/workflow_context.py
- dsl_parser/elements/misc.py
> RD-4131 Allow intrinsic functions in resource_tags

- cloudify_rest_client/operations.py
Those are going to be useful! (to me)
> RD-4292 More filters for listing operations

- cloudify_rest_client/blueprints.py
cloudify-cosmo/cloudify-manager#3584 adds this.
Let's also keep compat with pre-6.4 managers, and allow for returning
a 204 as well.
> RD-4482 rest-client: return execution from blueprints.validate

- cloudify/manager.py
This will allow switching over to the new tokens, before I remove API tokens entirely.
> RD-4486 Support new tokens and API tokens

- cloudify/dispatch.py
- cloudify/tests/test_dispatch.py
- cloudify/workflows/workflow_context.py
- dsl_parser/exceptions.py
Hmm. We could do even more work with making tracebacks nicer.
But for now, see these commits.
> RD-4502 Hide useless tracebacks (incl. DSLParsingExc)

- dsl_parser/functions.py
- dsl_parser/tests/test_functions.py
Instead of returning vague HTTP 500 error message, let's actually
present the cause of the error.
This code will affect also `get_attribute_list` and `get_attribute_dict`
functions.
> RD-4417 Better error message for `get_attribute`

- dsl_parser/constraints.py
Validate data types which require deployment_id constraint using default
value of deployment_id also in case no other constraints were provided.
> RD-4711 Always validate for default deployment_id

- dsl_parser/elements/operation.py
- dsl_parser/elements/workflows.py
- dsl_parser/tests/namespace/test_workflows.py
- dsl_parser/tests/test_parser_api.py
It doesn't do anything just yet, but now you can declare it in your dsl
> RD-4616 DSL: declare workflow.availability_rules

- cloudify_rest_client/log_bundles.py
> RD-3813 Remove trailing / from log bundle list

- cloudify/plugins/workflows.py
Just basic resume support, it'll only work if you're resuming the
only modification you have. The graph parts (install/uninstall) are
already resumable by themselves, we only need to make sure to not
re-create a deployment-modification unnecessarily.
> RD-4271 Make the scale workflow resumable

- cloudify/rabbitmq_client.py
Otherwise in snapshots we may be establishing hundreds or even thousands
of TLS connections in a fairly short time.
> RD-5088 Use a single session for rabbitmq client

- cloudify/rabbitmq_client.py
...not just to the requests that create the session :)
> rabbitmq_client: pass the CA file to every request

- cloudify/plugins/lifecycle.py
- cloudify/tests/resources/blueprints/test-has-operation.yaml
- cloudify/tests/test_context.py
- cloudify/workflows/workflow_context.py
A method to check if the node implements the given operation.
I'll need this to check if nodes actually implement the heal operation.
Also, replace all the `in node.operations` calls in lifecycle.py
with the calls to the new method.
> RD-4465 Add node.has_operation

- dsl_parser/constants.py
- dsl_parser/utils.py
This reverts commit bc106ae8bbdf28f107b9151a95110522cdae2e8e.
> RD-3901 Revert "RD-2804 Add secret input type to DSL (#881)"

- cloudify/workflows/local.py
When creating a dep-update, default the structure of the object
prior to storing it. Then, the caller doesn't need to pass all of this.
Also, return the created object.
Also also, when creating a deployment, also return the created env.
That one's mostly unrelated but makes for nicer caller code.
> RD-4466 Local: default attributes of dep-updates

- cloudify/plugins/workflows.py
The check_drift graph is going to be called from update, where we'll
have a special way of handling failures (if check_drift for a node
fails, we'll reinstall the instance). So, no need to throw the
error up.
...and also do the same for check_status. It's nicer than the
try/except.
> RD-4466 check_drift: add ignore_failure

- cloudify/plugins/lifecycle.py
- cloudify/tests/resources/blueprints/test-update-operation.yaml
- cloudify/tests/test_builtin_workflows.py
This is the counterpart to cloudify-cosmo/cloudify-common#3750
> RD-4466 Relationships update: rename the interface

- cloudify/workflows/workflow_context.py
Those properties CAN be useful to touch in workflow code, so let's
expose them.
> WorkflowNodeInstance: add .version and .runtime_props

- cloudify/context.py
- cloudify/manager.py
... and `system_properties` to `NodeInstance` objects.
> RD-5404 Add `drift` to `NodeInstanceContext`

- cloudify/tests/test_builtin_workflows.py
- cloudify/tests/test_context.py
- cloudify/tests/test_ctx_relationships.py
- cloudify/tests/test_decorators.py
- cloudify/tests/test_dispatch.py
- cloudify/tests/test_event.py
- cloudify/tests/test_install_agent_local_workflow.py
- cloudify/tests/test_install_new_agents_workflow.py
- cloudify/tests/test_lifecycle_retry.py
- cloudify/tests/test_local_get_attribute.py
- cloudify/tests/test_local_workflows.py
- cloudify/tests/test_local_workflows_init.py
- cloudify/tests/test_logs.py
- cloudify/tests/test_node_state.py
- cloudify/tests/test_operation_retry.py
- cloudify/tests/test_proxy.py
- cloudify/tests/test_task_retry.py
- cloudify/tests/test_task_retry_event_context.py
- cloudify/tests/test_task_serialize.py
- cloudify/tests/test_task_subgraph.py
- cloudify/tests/test_tasks_graph.py
- cloudify/tests/test_utils.py
- dsl_parser/tests/test_get_attribute.py
- script_runner/tests/test_ctx_wrapper.py
- script_runner/tests/test_script_runner.py
- setup.py
- test-requirements.txt
Now that we don't need to care about py2 anymore, this is easy!
> Remove testtools usage

- dsl_parser/framework/parser.py
> A hack to allow networkx 3.10 working with py3.10

- cloudify/plugin_installer.py
> plugin installer get_pth_dir: handle 3.10+ versions

- cloudify_rest_client/blueprints.py
- cloudify_rest_client/bytes_stream_utils.py
This means we can stop playing around with trying to encode labels as query params.
> RD-2873 Use multipart/form for blueprint upload

- cloudify_rest_client/blueprints.py
Otherwise the progress callback interface differs here from other places.
> Wrap progress callback for blueprints

- cloudify_rest_client/blueprints.py
The prepare function doesn't use it at all, the monitor does.
> Place the wrapped callback where it is needed

- dsl_parser/functions.py
- dsl_parser/tests/test_functions.py
Secret keys might be defined by an intrinsic function, e.g.
```yaml
{ get_secret: { get_sys: [deployment, id] } }
```
Before this patch, a helper function would fail because it used a variable of type `dict` as secret's key.
> RD-5974 Don't promptly clean unknown secrets

- cloudify/plugin_installer.py
Because of the comments in https://github.com/cloudify-cosmo/cloudify-common/pull/1162
> RD-6168 Install plugins using the best available Python version

- cloudify/plugins/workflows.py
- cloudify/tests/resources/blueprints/minimal_types.yaml
- cloudify/tests/test_builtin_workflows.py
Similar to #1172 but for uninstall.
> RD-6286 uninstall: allow filtering node-instances

- cloudify/plugins/workflows.py
- cloudify/tests/resources/blueprints/minimal_types.yaml
- cloudify/tests/test_builtin_workflows.py
This is the other part of cloudify-cosmo/cloudify-manager#3949
> Rd-6332 check_drift: default run_by_dependency_order to true

- cloudify_rest_client/blueprints.py
> RD-6401 Restclient: add blueprint.requirements

- cloudify_rest_client/secrets_providers.py
This is the client for cloudify-cosmo/cloudify-premium#922
> RD-6620 secrets_providers.list: allow filtering, pagination, etc

- cloudify/dispatch.py
- cloudify/tests/test_dispatch.py
The `dispatch.py` cruft is not interesting for the user. We can make the tracebacks a bit more useful by removing it.
Before:
```
Traceback (most recent call last):
File "/opt/mgmtworker/env/lib/python3.10/site-packages/cloudify/dispatch.py", line 337, in _execute_workflow_function
workflow_output = self.func(*self.args, **self.kwargs)
File "/opt/mgmtworker/env/lib/python3.10/site-packages/cloudify_system_workflows/deployment_environment.py", line 268, in create
_check_blueprint_requirements(ctx, deployment, bp)
File "/opt/mgmtworker/env/lib/python3.10/site-packages/cloudify_system_workflows/deployment_environment.py", line 222, in _check_blueprint_requirements
raise ValueError(
ValueError: Environment env does not have the required capabilities: cap1.key1.0
```
After:
```
File …
```
> RD-6693 Skip first line of the traceback

- cloudify/plugins/lifecycle.py
- cloudify/plugins/workflows.py
- cloudify/test_utils/local_workflow_decorator.py
- cloudify/tests/resources/blueprints/minimal_types.yaml
- cloudify/tests/test_builtin_workflows.py
- cloudify/tests/test_context.py
- cloudify/workflows/local.py
This backports the following tickets to 6.4.2:
- RD-6652
- RD-6634
- RD-6285
- RD-6286
- RD-6287
[RD-6652]: https://cloudifysource.atlassian.net/browse/RD-6652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6634]: https://cloudifysource.atlassian.net/browse/RD-6634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6285]: https://cloudifysource.atlassian.net/browse/RD-6285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6286]: https://cloudifysource.atlassian.net/browse/RD-6286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6287]: https://cloudifysource.atlassian.net/browse/RD-6287?atlOrigin=eyJpIj …
> RD-6588 6.4.2 backports

- cloudify_rest_client/resources.py
* during a download if a file is missing on manager, it is also removed from deployment's workdir local copy
* during upload if a file was removed locally, so it would from the manager
> RD-6614 Deployment workdir sync removes obsolete files

- cloudify/context.py
- cloudify/utils.py
- cloudify/workflows/workflow_context.py
So far we've been always only using rest port from the envvars, but let's make it more similar to rest_host.
> RD-6586 Use rest_port from ctx

- cloudify/tests/test_builtin_workflows.py
- cloudify/tests/test_tasks_graph.py
- cloudify/workflows/tasks.py
- cloudify/workflows/tasks_graph.py
> RD-6930 Don't run tasks with failed dependencies

- cloudify/workflows/workflow_context.py
Just expose those two parameters. They're going to be useful in cloudify-cosmo/cloudify-manager#4060
> RD-6908 WorkflowNode: expose instance counts

- cloudify_rest_client/executions.py
Sets the concurrency for a group
> RD-7042 Add client.execution_groups.set_concurrency

- cloudify_rest_client/audit_log.py
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-common/pull/1254
> RD-7142 Add audit_log.ref_identifier field

- cloudify/utils.py
Let's have the same default for both.
> RND-323 Default the fileserver proto to the restservice proto

- cloudify_rest_client/snapshots.py
This is a slightly modified cherry-pick of https://github.com/cloudify-cosmo/cloudify-common/pull/1262 (the default value for legacy parameter is set to True).
> RND-363 Snapshot create `legacy` parameter

- dsl_parser/elements/imports.py
- dsl_parser/import_resolver/abstract_import_resolver.py
- dsl_parser/tests/test_plugin_properties.py
- dsl_parser/utils.py
> RND-430 dsl_parser: download resources from the fileserver

- dsl_parser/elements/imports.py
Don't obscure the actual error
> RD-430 reraise DSL fetching error

- dsl_parser/elements/imports.py
Don't obscure the actual error
> RD-430 reraise DSL fetching error (#1268)

- cloudify/context.py
- cloudify/endpoint.py
- cloudify/manager.py
- cloudify/mocks.py
This is going to be immediately used in agents, for storing the agent install script
> RND-389 Expose ctx methods for uploading & deleting deployment files

- cloudify_rest_client/agents.py
- cloudify_rest_client/blueprints.py
- cloudify_rest_client/constants.py
- cloudify_rest_client/deployment_updates.py
- cloudify_rest_client/deployments.py
- cloudify_rest_client/events.py
- cloudify_rest_client/execution_schedules.py
- cloudify_rest_client/executions.py
- cloudify_rest_client/filters.py
- cloudify_rest_client/inter_deployment_dependencies.py
- cloudify_rest_client/node_instances.py
- cloudify_rest_client/nodes.py
- cloudify_rest_client/operations.py
- cloudify_rest_client/permissions.py
- cloudify_rest_client/plugins.py
- cloudify_rest_client/plugins_update.py
- cloudify_rest_client/secrets.py
- cloudify_rest_client/secrets_providers.py
- cloudify_rest_client/sites.py
- cloudify_rest_client/tenants.py
- cloudify_rest_client/user_groups.py
- cloudify_rest_client/users.py
- cloudify_rest_client/utils.py
These are (going to be) used to create snapshots
> RND-364 Implement cloudify_rest_client dump() methods 

- cloudify_rest_client/executions.py
> RND-652 restclient: add _include to excgroups.get

- cloudify/context.py
- cloudify/endpoint.py
- cloudify/plugins/workflows.py
- cloudify_rest_client/agents.py
- cloudify_rest_client/blueprints.py
- cloudify_rest_client/constants.py
- cloudify_rest_client/deployment_updates.py
- cloudify_rest_client/deployments.py
- cloudify_rest_client/events.py
- cloudify_rest_client/execution_schedules.py
- cloudify_rest_client/executions.py
- cloudify_rest_client/filters.py
- cloudify_rest_client/inter_deployment_dependencies.py
- cloudify_rest_client/node_instances.py
- cloudify_rest_client/nodes.py
- cloudify_rest_client/operations.py
- cloudify_rest_client/permissions.py
- cloudify_rest_client/plugins.py
- cloudify_rest_client/plugins_update.py
- cloudify_rest_client/secrets.py
- cloudify_rest_client/secrets_providers.py
- cloudify_rest_client/sites.py
- cloudify_rest_client/tenants.py
- cloudify_rest_client/user_groups.py
- cloudify_rest_client/users.py
- cloudify_rest_client/utils.py
- dsl_parser/elements/operation.py
- dsl_parser/functions.py
- dsl_parser/tasks.py
- dsl_parser/tests/test_parser_api.py
Bring up all the PRs from master onto 7.0.1
> Sync 7.0.1 with master

- cloudify_rest_client/log_bundles.py
* Fix log-bundle archive path
* Log-bundle upload expected HTTP response is 201
> NE-7793 LogBundlesClient.upload_archive fixes

- cloudify_rest_client/log_bundles.py
This is a cherry pick of #1316 and #1317.
> NE-7793 Implement log-bundles archive upload

- cloudify/cluster.py
If we're not gonna retry, let's reraise the last received error, not a generic one, so that try/except in the caller, might examine the real statuscode etc.
With this, sanitycheck should pass. Without it, the "except on 404" clause in agent_utils/_initialize_rabbitmq_user cannot work.
> Cluster client: reraise the real error

- cloudify/amqp_client.py
This ports fusion-e/fusion-common#93 to cloudify-common
> NE-23256 Fix AMQP consumers deadlock

- cloudify/workflows/local.py
- cloudify/workflows/workflow_context.py
- cloudify_rest_client/node_instances.py
- dsl_parser/rel_graph.py
- dsl_parser/tests/scaling/test_multi_instance.py
Port NE-30898 from fusion-e
https://github.com/fusion-e/fusion-common/pull/119 https://github.com/fusion-e/fusion-common/pull/122
> NE-30898 node_instances.create_many: opt response

- setup.py
to match other cloudify's packages iohttp version in requirements.txt
> Set iohttp to a fixed version 
