cloudify-cosmo/cloudify-common

cloudify/amqp_client.py

Add a connect timeout, and socket_timeout for pika. This means each
connection attempt will take a limited amount of time, and after
connect_timeout time has passed, we'll throw an error.
In case of a blocking .consume(), this error will simply be raised.
In case of .consume_in_thread, the error must be extracted out to the
calling thread, and raised there.

amqp_client: add connect_timeout

---

cloudify/amqp_client.py

This happens when AMQPConnection is used from places that aren't the
agent worker (eg. cfy-agent daemons)

CY-199 Don't update env vars if they're not set

---

cloudify/amqp_client.py

just `.wait()`-ing on a event blocks signal handling, so eg. ctrl+C
won't have an effect during that time. Which means if an exception happens
inside the connect sequence (currently can only really happen due to
programming error, but still), there's no easy way to even close the program.

CY-199 consume_in_thread: poll instead of waiting indefinitely

---

cloudify/amqp_client.py

Iterating _connection_params loads the params from files, so it might
well throw exceptions. Those must be handled, and popped up to the
calling thread, otherwise it'll just hang.
This change generalizes the ._error to also include those errors, and
pass them up as before.

CY-199 amqp_client connect: catch exceptions from making params

---

cloudify/workflows/tasks.py

Otherwise we will use the old object on retries

Need to refresh the async_result

---

cloudify/amqp_client.py
cloudify/utils.py

`evt.wait()` in python 2.6 always returns None, so doing
`if evt.wait(0.5)` is never true, and in a loop, leads to a busyloop
which never allows the code to continue

Python 2.6-compatible waiting for event

---

cloudify/amqp_client.py
cloudify/workflows/workflow_context.py

The callback is called in that thread, it makes no sense to join
from there

TaskDispatcher: dont join the consumer thread from callback

---

cloudify/utils.py

version_info might well be eg. (2,6,6) which is > (2,6),
but it's still not python 2.7

utils version check: handle minor/patch versions

---

cloudify/dispatch.py

Because of the change in #26, `self.func` no longer raises, so we
need to explicitly call `self.get_func()` in order to raise helpful
errors

CY-270 Need to also validate operation func

---

cloudify/cluster.py

This can happen eg in the 2_1 tests in cloudify-manager, where we install
an old version of rest-client

Handle old rest-client versions

---

cloudify/amqp_client.py
cloudify/workflows/workflow_context.py

Implement a `publish` method on the `AMQPConnection` that makes
sure errors while publishing are bubbled up, and use that method
in handlers.

amqp_client: forward errors to the calling thread

---

cloudify/dispatch.py

To make it do at least as much as regular cancel

Force cancel: also stop the graph execution

---

cloudify_rest_client/executions.py

Only when status field is available, we need to set status_display for backward compatibility

CY-444 : Added a check for status_displpay appearance

---

cloudify/amqp_client.py

When we connect to the new cluster leader, set its IP in the cluster
config file so that the restclient/fileserver client can use it

CY-502 amqp_client: set_cluster_active

---

.gitignore
cloudify/tests/test_builtin_workflows.py
cloudify/tests/test_decorators.py
cloudify/tests/test_local_workflows.py
cloudify/tests/test_proxy.py
dsl_parser/tests/test_get_secret.py
script_runner/tests/test_script_runner.py
tox.ini

The switch was done because of lose of development of nosetests by it's maintainers.
Redesign of unit tests classes according to the best practices.
Incorporating distributed run of unit tests for speed gain when possible.

CY-430 : Switching nosetests to pytest

---

cloudify/dispatch.py

On failure, validate_workflow_func will call _workflow_failed, which
must be in workflow ctx to be able to send the event/update

dispatch validate_workflow_func: run in workflow context

---

cloudify/workflows/tasks.py

After requesting the proxy tenant, check that we did receive
the credentials.
If the user isn't allowed (permissions-wise) to access them, throw
an error.

CY-599 Validate the proxy tenant

---

tox.ini

This is done because of a recent bug in coverage  5.0a3 version
https://github.com/nedbat/coveragepy/issues/716

coverage: setting to a specific version

---

cloudify/workflows/workflow_context.py

Don't send messages to the mgmtworker using the tenant user on
vhost /, use the mgmtworker (config) user instead

TaskDispatcher: for mgmtworker queue, use the mgmtworker user

---

dsl_parser/elements/imports.py
dsl_parser/import_resolver/abstract_import_resolver.py
dsl_parser/parser.py
dsl_parser/tests/test_parser_api.py

- Added recognition of blueprint catalog import.
- Removed not needed functions in the abstract resolver.
- Added the ability to parse a blueprint and receive the merged blueprint, this is for being able to import a blueprint from the catalog.
- Add fixing CY-689: description from imported blueprint should not try to overwrite the existing one

CY-680: adding support for blueprint import

---

cloudify_rest_client/blueprints.py

- This is done to preserve backwards compatibility for the rest api

CY-693 : moving the force flag to query line args

---

dsl_parser/exceptions.py
dsl_parser/functions.py
dsl_parser/tests/test_inputs.py

`get_input` now behaves as `get_property` but also supports the old
syntax.
This enables acquiring a nested property of a provided input, in the
same way that get_property does.

CY-746 Add ability to get_input nested property

---

cloudify/agent_utils.py
cloudify_rest_client/agents.py

* While restoring agents, it will create the agent record in the DB but
will not creare the rabbitmq user.
* Later in the restore we run the restore_amqp script and rabbitmq users
will be created.

CY-763 Add create_rabbitmq_user parameter to agents create

---

dsl_parser/elements/imports.py
dsl_parser/holder.py
dsl_parser/tests/test_cloudify_basic_types_mark.py

- Adding missing handling when using a merged blueprint which contains
Cloudily basic types.
- Also adding handling for merging metadata element
- Fixed a bug for imports graph creation

CY-642: refactor preventing adding namespace to Cloudify basic types

---

dsl_parser/import_resolver/default_import_resolver.py
dsl_parser/tests/test_deafult_import_resolver.py

Falling back to the original url can now be configured from the
pctx level

CY-874 default import resolver: fallback - make configurable

---

cloudify/workflows/tasks_graph.py

A single graph might be stored multiple times in case it is reused
in a workflow. It will then be stored with different names.

Allow storing a graph multiple times

---

cloudify/workflows/tasks.py
cloudify/workflows/workflow_context.py

Places that send a task must do the same as the tasks graph and set
the state correctly.
Those non-tasks-graph places don't support resuming.

Set task state to SENDING when sending it not from a tasks-graph

---

cloudify/cluster.py
dsl_parser/elements/imports.py
script_runner/tasks.py

By default, expose the exec temp directory to the script, so that
`mktemp` calls inside the script use it

CY-1013 Expose TMPDIR to the script

---

cloudify/plugins/workflows.py

Because builtin workflows such as `stop` pass argument positionally
instead of by name

CY-1020 execute_operation: also pass *args

---

dsl_parser/elements/imports.py
dsl_parser/elements/node_templates.py
dsl_parser/elements/operation.py
dsl_parser/elements/relationships.py
dsl_parser/elements/workflows.py
dsl_parser/tests/abstract_test_parser.py
dsl_parser/tests/namespace/test_node_templates.py
dsl_parser/tests/namespace/test_workflows.py
dsl_parser/tests/utils.py
dsl_parser/utils.py

* Remote resource (blueprint import) can have scripts, but in the current
parsed script there is no need to verify those exists.
* Adding fix for namespced script plugin name in workflows
* Clearing up the error msg if there is no plugin or script resource in not
found for an operation.

CY-1028 : fixing the validation of remote resource scripts

---

script_runner/tasks.py

By default, expose the exec temp directory to the script, so that
`mktemp` calls inside the script use it

 CY-1013 Expose TMPDIR to the script

---

dsl_parser/constraints.py
dsl_parser/tasks.py
dsl_parser/tests/test_inputs.py
dsl_parser/utils.py

- Fixes regex string validation: it now uses basestring and not str.
- Fixes basic data types not validated during deployment creation.

CY-933 Fix input validations

---

dsl_parser/interfaces/utils.py
dsl_parser/tests/test_relationships.py

- which was already validated in the parsing process by the parse_value util

CY-1259: removing un-needed check for input types

---

cloudify/context.py
cloudify/dispatch.py
cloudify/endpoint.py
cloudify/tests/mocks/mock_rest_client.py
cloudify/tests/test_dispatch.py
cloudify/workflows/tasks.py

For remote tasks, it is the agent that is updating the operation
state. This way, the state will be updated even if the workflow
was cancelled.
Additionally, TASK_STARTED state now makes sense as well!

CY-1321 Update remote operation state on the dispatch side

---

cloudify/dispatch.py

That state was unused, but now we have a way to actually set it,
so that we can differentiate sent and started tasks

Set TASK_STARTED in remote tasks

---

cloudify/cluster.py

We have a connect timeout so that if a manager node is down, other
can be tried.
However, there's no reason to have a read timeout. Once we connected,
wait for the response as long as it takes.
(This is also what the CLI does)

ClusterClient: no read timeout

---

cloudify/amqp_client.py
cloudify/dispatch.py
cloudify/exceptions.py

When a task is kill-cancelled, the other side is killed as well,
so there's nobody who can receive the "error: process was killed"
response, and that response is stuck in the queue.
If then a resume is called, that response is pulled, and the resume
immediately fails due to it.
With these changes, processes that are kill-cancelled are going to
send no response at all, and are going to delete the response queue
right away.

Send no response when a task is kill-cancelled

---

cloudify/plugins/workflows.py
cloudify/tests/test_builtin_workflows.py
cloudify/workflows/tasks_graph.py

This means that usages of execute_operation (in the restart workflow)
will have distinct names by default, because they run different
operations.
This doesn't change anything for other usages of execute_workflow,
because the name is just an opaque identifier, nothing really cares
if it's "execute_operation" or "execute_operation_cloudify.lifecycle.create"
Additionally, that means that looking at the operations table in the
db will be nicer, with this info in the name

CY-1525 execute_operation: add operation name to the graph name

---

cloudify/plugins/workflows.py

Those workflows use a tasks graph and so they are resumable.
(of course, the operations inside of them may still not be resumable,
but the workflow itself is)
This requires #341

CY-1411 Make start/stop/restart workflows resumable.

---

cloudify/utils.py
cloudify/workflows/workflow_context.py
cloudify_rest_client/tenants.py

Instead of storing the credentials in operation context, which
might be stored in places that we don't want to store credentials in
(eg. the operations table), get the credentials via rest when
sending.
Also declare the credential fields on the restclient Tenant object -
they were there before (since CY-599), but undeclared

CY-1043 Get rabbitmq credentials from rest when sending tasks

---

cloudify/context.py
cloudify/logs.py

For backwards compatibility, ctx.tenant must return the whole tenant
and not just the name.

ctx.tenant: return full tenant if available

---

cloudify/workflows/local.py
dsl_parser/functions.py
dsl_parser/tests/abstract_test_parser.py
dsl_parser/tests/namespace/test_functions.py
dsl_parser/tests/test_get_attribute.py
dsl_parser/tests/test_get_capability.py
dsl_parser/tests/test_get_secret.py
dsl_parser/tests/test_outputs.py
dsl_parser/tests/test_register_function.py

Instead of passing all the methods in separately, pass a single "Storage"
object.
This is factored out of #356

CY-1732 Functions evaluation: pass a single storage object

---

dsl_parser/functions.py
dsl_parser/tests/abstract_test_parser.py

instead of sometimes being dicts and sometimes objects, they're now
always just dicts

dsl-parser functions: nodes and instances are dicts

---

cloudify_rest_client/snapshots.py

* The parameter include_metrics was removed from `client.snapshot.create`
and from the unit tests that uses this parameter when creating a snapshot.
* Unit tests of old client versions were broken
* We now add include_metrics as a default param to snapshot create.
This is a deprecated parameter, which is kept only for old client versions unit tests.

CY-1881 Add include_metrics as a default param to snapshot client

---

cloudify/context.py
cloudify/dispatch.py
cloudify/endpoint.py
cloudify/tests/mocks/mock_rest_client.py
cloudify_rest_client/operations.py

When setting operation state to "started", we might learn that the
operation was already started before. In that case, we know it's a
resume, so we can set it as one.

CY-1959 If operation was started before, mark it as a resume

---

.circleci/config.yml
setup.py

0.12.7 uses some deprecated syntax which results in warnings

Bump bottle version to 0.12.18

---

cloudify/ctx_wrappers/ctx-py.py
cloudify/dispatch.py
cloudify/endpoint.py
cloudify/event.py
cloudify/proxy/client.py
cloudify/proxy/server.py
cloudify/tests/test_context.py
cloudify/tests/test_local_workflows.py
cloudify/tests/test_utils.py
cloudify/utils.py
cloudify/workflows/local.py
script_runner/tests/test_ctx_wrapper.py

Only where absolutely necessary (for now)
See each commit for details

CY-2430 Py3 porting: unicode/bytes changes

---

cloudify_rest_client/executions.py

Properly restore scheduled executions from snapshots.  Add `requeue`
action for reinserting executions to execution queue after snapshot
restoration.

CY-2435 Restore scheduled tasks from snapshot

---

.circleci/config.yml
test-requirements.txt

So that CI is able to run. CI is useful, or so I hear.

CI: pin virtualenv, testtools versions

---

test-requirements.txt

march 14 2020, testtools 2.4.0 was released, which drops py2.6 compat
pin to 2.3.0 which is the last 2.6-compatible version

test-reqs: pin testtools version

---

cloudify/exceptions.py

The message has to be unicode, because parts of it can be unicode.
And there's no reason to have bytes there anyway.
Also, drop the `__str__`, because that's the same as using the
baseclass one

CommandExecutionException: handle unicode message

---

cloudify_rest_client/responses.py

It's not there in py3 anymore, and we don't use it
We could just as well use functools.cmp_to_key but it's rare enough
that I don't want to pay the performance cost without alerting the
caller. But I'm open to having my mind changed on this later.
It needs to be a typerror like that, and not just removing the arg,
because cmp is the first arg, so a call like `.sort(f) would then
silently change f from being cmp to being key :(
To be dropped entirely in 5.2

response.sort: stop supporting cmp=

---

cloudify/cryptography_utils.py

It would be more pure to use bytes, but examining usage sites,
they all want to deal with unicode, so it's more useful to do it
like this

crypto_utils: work with unicode

---

dsl_parser/tasks.py
dsl_parser/tests/test_inputs.py

When using datatype that has default values, in a blueprint and overwriting
only part of the properties in an input file, the other properties were
missing from the node properties.
This patch fixes that issue by using parsed input's value instead of
original one.

CY-2313 Use blueprint detatype default values

---

cloudify/decorators.py
cloudify/tests/test_decorators.py

see each commit
main point is that just setting `manager.get_rest_client = blabla` inside of
one test and never clearing it is absolutely wrong, because that means
the tests running after it, will now be able to depend on it
so instead, just use `@patch` properly

test_decorators.py: use mocks properly

---

cloudify/plugins/workflows.py
cloudify/tests/resources/blueprints/test-scale-blueprint.yaml
cloudify/tests/test_builtin_workflows.py
cloudify/workflows/workflow_context.py

Enable rollback of started (stalled) deployment modifications before
scaling workflow

CY-2314 Rollback started dep-mods on scale_entity

---

dsl_parser/framework/elements.py

start_line is None in case of a very malformed blueprint, and in that case,
we can't compare that to 0

dsl_parser error handling: don't die on None start_line

---

cloudify_rest_client/utils.py

When creating a tar archive for a blueprint, add the files pointed-to by links,
instead of adding links

blueprint upload: dereference links

---

cloudify/plugins/lifecycle.py

Make reinstall_node_instances (part of update workflow) use its own execution
graph not the one generated for uninstall and install steps.

CY-2688 Fix lifecycle reinstall_node_instances

---

cloudify_rest_client/plugins.py

Enabling setting uploaded plugin's `title` field which will be used e.g.
in UI for presentation purposes in Topology widget.

CY-2774 Add plugin_title in PluginsClient.upload()

---

cloudify/amqp_client.py
cloudify/event.py
cloudify/logs.py
cloudify/tests/test_event.py
cloudify/tests/test_logs.py

Both database (amqp) and console logs can now handle Unicode messages.

CY-2698 Allow Unicode in Cloudify logs

---

cloudify/plugins/workflows.py
cloudify/workflows/workflow_context.py

In scale-like workflows (which can be custom workflows written
by the user!), it is always required to refresh node instances
after starting the scale, so that the local process gets the
newly-created node instances.
Without refreshing, it doesn't have them, and so it can't install
them.
Since it is always required, let's just make it happen automatically.

CY-2900 start deployment modification: refresh node instances

---

cloudify/snmp/snmp_trap.py
setup.py

It's only needed in the mgmtworker, for custom hook-called functions

Make pysnmp optional

---

cloudify/dispatch.py
cloudify/utils.py
cloudify/workflows/workflow_context.py

When running an operation, check if the plugin is installed,
and if it's not - install it then.
This is as opposed to the previous approach of always installing
plugins up-front.
Also, pass through the plugin source to operations.

CY-3015 Install plugins on first use

---

cloudify_rest_client/cluster.py

As status-reporter service is now entirely different (pull instead of push),
no active reporting is required.

Remove report_node_status

---

cloudify/dispatch.py

Only encode env vars on py2

---

cloudify/tests/test_context.py
cloudify/utils.py

Instead of just checking .isdir, also look for the plugin.id file.
Otherwise it will be just a directory and not a directory containing
a plugin.
In practice, it will be a plugin that is not fully installed yet,
so we should go to the installer, which will do the locking-and-waiting
dance.

When checking for plugin dir, check for the marker file as well

---

cloudify/context.py
cloudify/dispatch.py
cloudify/tests/test_context.py
cloudify/tests/test_local_workflows.py
cloudify/utils.py

This makes getting the plugin directory a bit simpler.
Plugins are now installed in, for managed plugins:
`/opt/mgmtworker/env/plugins/<tenant>/<plugin name>/<version>`
and for source plugins:
`/opt/mgmtworker/env/source_plugins/<tenant>/<plugin name>/<version>`
Also, visibility isn't needed, because plugins are installed for
the _using_ tenant anyway. And if visibility isn't global, then
the plugin can't be downloaded or used anyway.

Refactor utils.plugin_prefix

---

cloudify/utils.py

default to False, not to None. It's false in case of a missing context, why would
it not be false in case of a missing attr?
in practice, this cases many agent tests to fail, because they assert
on this being false. Which is not very smart of them, but eh.

get_is_bypass_maintenance: default to False

---

cloudify/context.py
cloudify/utils.py
cloudify/workflows/workflow_context.py

Make this a real attribute, so that 'external' methods
(the one in utils.py) use a public attribute on the context,
instead of touching the internal ._context
This matters because quasi-contexts such as the CancelCloudifyContext
(which is used for kill-canceling) or the PluginInstallContext
(plugin force-installing) declare some attributes, and ._context
is not one of them. I want to make those quasi-contexts declare
.bypass_maintenance, I don't want to make them declare an
'internal' .context

contexts: make bypass_maintenance a public attribute

---

cloudify/dispatch.py

package_name is not always present after all

Plugin installer: fallback to plugin.name

---

cloudify/cluster.py
cloudify_rest_client/client.py

In case a file was not replicated, try the other managers.

ClusterClient: retry file downloads on 404

---

cloudify/utils.py

This restores _is_plugin_dir to as it was before #512
Just checking if the dir exists is not enough because maybe the
plugin is currently being installed by another process(/thread)
The id file is created after installation is done, so only when that
exists, the plugin is done and ready to use

plugin_prefix: only return valid plugin dirs

---

cloudify/utils.py

don't compare versions between plugin directories and other files
that just happen to be in that directory (here: the lockfiles)

_find_versioned_plugin_dir: only consider plugin directories

---

cloudify/dispatch.py

That's a 3.2 (!) back-compat thing. Because that's what this was called back then.

add agent_installer to PREINSTALLED_PLUGINS

---

cloudify/dispatch.py
cloudify/exceptions.py
cloudify/plugin_installer.py
setup.py

The plugin installer code should really live in common, because:
- otherwise we have a cyclic dependency where common needs agent, but agent needs common
- and also we'll be able to use the plugin stuff in cfy local

Move plugin installer code to common

---

cloudify/plugin_installer.py

Plugin dirs are `/opt/mgmtworker/env/plugins/<tenant>/<plugin>/<version>`
When the `<version>` dir is deleted, if this was the last one for that
plugin, also delete the `<plugin>` dir as well

Plugin uninstall: remove parent dir if empty

---

cloudify/manager.py
cloudify/tests/test_context.py

If one of the managers returns 404, also try the other ones:
the manager we've tried might have not replicated the files yet,
but perhaps the other managers have it already.

CY-3237 Get resource: try all managers in a cluster

---

cloudify/tests/test_tasks_graph.py
cloudify/workflows/tasks_graph.py

We have the logic that if a task is already finished, we don't restore it to the graph.
However, if the task was failed, the subgraph would've been failed as well. And when we
resumed that failed task with reset-operations, the subgraph wouldn't be part of
the graph.
This makes it so that a subgraph to which a resumed task belongs, is also going to
be resumed. Its state is reset to STARTED.
Also added a few unittests.
Note that commit 2 implements the idea, but commit 3 refactors it, so it probably
doesn't make sense to read too much into commit 2 on its own.

CY-3419 Restore operations belonging to finished subgraphs

---

cloudify/tests/test_tasks_graph.py
cloudify/workflows/tasks_graph.py

Every task belonging to a subgraph will go into the
`while op_descr.containing_subgraph` loop. Multiple tasks
in the same subgraph will each go there, and we must make
sure that they all get the _same_ subgraph object, as opposed
to each getting a new subgraph, which would only contain
that one task.
Putting the `if` inside of `_restore_operation` instead of
in the caller, because that function is called twice there,
so I'd have to `if` twice there.
This fixes the integration test:
agentless_tests/test_resume.py::TestResumeMgmtworker::test_nonresumable_mgmtworker_op

CY-3419 Restore graph: only restore each subgraph once

---

cloudify/plugin_installer.py

All of this code has some kind of "ignore errors" except for the
os.listdir call. Which will break when the directory doesn't exist,
when trying to uninstall a plugin which isn't installed.
Let's not break, and instead add a try/except around that listdir
as well.

Plugin uninstall: don't break on missing directories

---

cloudify/workflows/workflow_context.py

Similar to ctx.download_resource.
This is because we sometimes _do_ need a download_resource on the
workflow level - specifically, when installing source plugins, we'll
use download_resource, on whichever context we're in - if it's an
operation function, then CloudifyContext, but if we're in a
workflow context, because we're installing a plugin containing the
workflow function, then we'll be using a WorkflowContext. So it
needs to be defined there as well.
But in principle any workflow function code can use download_resource.
And it's surprising this feature hasn't come up before.

CY-3455 Add workflow_ctx.download_resource

---

cloudify_rest_client/client.py

204 means no content, so no reason to try and json-decode it.
There's no content. Don't even try.

REST Client: handle 204 responses

---

cloudify/workflows/tasks.py

In the various workflow graphs, there are still NOP tasks
used for structuring the graph and keeping dependencies.
During graph restore, we key the dicts by task id, and so the
task id must be passed through and set. Hence making sure the
kwargs are passed.
Since the NOP tasks are used for structuring, they must go into
the restored graph as well. Hence storing them as pending after all.
They will always go into the graph, and possibly be executed
immediately after restoring. But they will always be there and will
influence the ordering of other operations as they should.

CY-3456 NOP tasks: pass through the id, keep them in the graph

---

cloudify/plugins/lifecycle.py

When the install workflow is resumed, if we are to re-send
the create operation, send a delete first. If we are to re-send
the stop operation, send stop first.

CY-3456 Smart resume for the install workflow

---

cloudify/plugin_installer.py
cloudify/utils.py

Moving the plugin state updates to here, from
cloudify_agent.operations, because implicit (on-first-use) calls
to install/uninstall also need to update the plugin state.
Packaged the state-updating part into a decorator, too.

CY-3534 Manage plugin state in plugin_installer

---

cloudify/plugin_installer.py
cloudify/utils.py

The main point is running this on _managed_ plugins because only
they have an id, so it can only be run on them anyway.
See each commit for details.

CY-3534 manage_plugin_state fixes

---

cloudify_rest_client/client.py

As opposed to urlsafe_b64encode.
No reason for this to be urlsafe. At all.
Also, urlsafe breaks, because flask uses the non-urlsafe version
when decoding: https://github.com/pallets/werkzeug/blob/bbc5cbb8390d8d9de4fff42456cab3d91b85b584/src/werkzeug/http.py#L622
(this is for making `request.authorization`, which we then use).
Also, the basic auth rfc (RFC 7617) talks about using the plain version
of base64, not an urlsafe variant.
It needs to be encoded the same way it's going to be decoded.

CY-3552 Use b64encode for creating credentials.

---

cloudify/utils.py

We used to use both randomly, let's standardize to this one,
and forget about the other one.

Use the AGENT_NAME envvar instead of CLOUDIFY_DAEMON_NAME

---

cloudify/dispatch.py
cloudify/error_handling.py
cloudify/event.py
cloudify/tests/test_dispatch.py

Retry tracebacks are uninteresting. No need to display them ever.

CY-3584 Hide OperationRetry traceback

---

cloudify/dispatch.py
cloudify/error_handling.py
cloudify/exceptions.py
cloudify/tests/test_dispatch.py
cloudify/tests/test_install_new_agents_workflow.py
cloudify/tests/test_tasks_graph.py
cloudify/workflows/tasks_graph.py

- specialcase the exception
- hide its traceback
- stop wrapping the exception in a dict + another exception kind

CY-3584 Hide the 'workflow failed' traceback

---

cloudify/cluster.py

We need to isolate ourselves from outside changes to the hosts list,
that's why we can copy it.
Main reason of the "outside changes" is another ClusterClient
running concurrently, and doing the shuffle() as well.
This can lead to the client contacting the same manager multiple
times, and skipping over some managers, depending on the shuffle luck.

CY-3589 ClusterClient: copy the hosts list

---

cloudify_rest_client/deployment_updates.py

TemporaryFile() by default takes bytes, so we can't json.dump()
into it, because that tries to write unicode.
We can't make it a unicode-kind file, because requests, if it gets
a file, wants a binary file.
Instead, we can just pass the json-encoded string directly, without
a file.
This fixes the integration test:
`integration_tests/tests/agentless_tests/test_runtime_functions.py::TestRuntimeFunctionEvaluation::test_change_flag_update`

restclient: dep-update: pass json mime-encoded body

---

cloudify/plugin_installer.py

If we don't have the plugin details, attempt to fetch them.
This is similar, and uses the same method as, installing the plugin.
This is because sometimes (eg. in the uninstall in plug-update)
we only get package-name and package-version but not the id.

CY-3619 Plugin state update: fetch plugin if missing

---

cloudify/workflows/tasks.py

Store these params as well, next to other ones.
Embarassing that we ever missed them.
This means that resumed tasks will now correctly handle retry
counts and intervals.

CY-3618 Task store/restore: also keep track of retries

---

cloudify/rabbitmq_client.py

So that internal mutations don't affect the outside world.
Same reasoning as #567

RabbitMQClient: copy the list of hosts

---

cloudify/manager.py
cloudify/tests/test_context.py

get_resource is supposed to try 3 paths:
- deployment-local  (for all managers)
- blueprint-local  (for all managers)
- manager-global  (for all managers)
..for up to `3 * len(managers)` calls in a cluster.
It used to, if one of the managers was offline, throw a NonRecoverable
on possibly the deployment-local stage.
This meant that if one manager was offline, it was impossible to
use get_resource to get blueprint-local or manager-global
resources.
Instead, make sure that get_resource never throws nonrecoverable,
always throws httpexception if it doesn't found, but most importantly-
always tries all managers, even if some managers are offline.
(I'll keep that `if` as 404 for now, I don't think that needs to
be made more lenient)

get_resource: try all possible paths

---

cloudify/plugin_installer.py

Rewrite the `get_managed_plugin` logic.
1) Don't pass platform/distro/release filters. Fetch all plugins for the given name/version and filter them out clientside instead. This is because the filtering logic is too complex to be encoded in just filters (with `any` and `manylinux`)
2) Allow `manylinux` plugins on linux platforms
3) If plugin's `.distribution` or `.distribution_release` are not set, then ignore them
Paraphrasing the "is supported" logic:
- plugins that are `any` are always supported
- on non-linux, `.supported_platform` must match exactly
- on linux, `manylinux` is always supported
- on linux, if distro & release are specified, they must match exactly

CY-3646 Allow installing manylinux plugins

---

dsl_parser/tasks.py
dsl_parser/tests/namespace/test_functions.py

For some blueprints default values for the inputs are stored inside
data_types.  Before this patch those were not taken into consideration
while setting plan inputs.
The new approach is parsing an empty value in case no input or input's
default value were provided.

RD-326 Blueprint input from datatypes handling

---

cloudify/tests/test_utils.py

we wrote 14 bytes, we expect 14 bytes back. No idea why 25.

test_get_folder_size_and_files: expect same amount of bytes as written

---

.circleci/config.yml
cloudify/amqp_client.py
cloudify/dispatch.py
cloudify/plugins/lifecycle.py
cloudify/plugins/workflows.py
cloudify/test_utils/local_workflow_decorator.py
cloudify/tests/resources/blueprints/execute_operation-blueprint.yaml
cloudify/tests/resources/blueprints/install-new-agents-blueprint.yaml
cloudify/tests/resources/blueprints/minimal_types.yaml
cloudify/tests/resources/blueprints/not_exist_op_workflow-blueprint.yaml
cloudify/tests/resources/blueprints/test-blueprint-ignore-failure.yaml
cloudify/tests/resources/blueprints/test-heal-correct-order-blueprint.yaml
cloudify/tests/resources/blueprints/test-lifecycle-retry-blueprint.yaml
cloudify/tests/resources/blueprints/test-lifecycle.yaml
cloudify/tests/resources/blueprints/test-relationship-order-blueprint.yaml
cloudify/tests/resources/blueprints/test-subgraph-blueprint.yaml
cloudify/tests/resources/blueprints/test-uninstall-ignore-failure-parameter-blueprint.yaml
cloudify/tests/test_builtin_workflows.py
cloudify/tests/test_context.py
cloudify/tests/test_ctx_relationships.py
cloudify/tests/test_dispatch.py
cloudify/tests/test_operation_retry.py
cloudify/tests/test_task_serialize.py
cloudify/tests/test_tasks_graph.py
cloudify/workflows/tasks.py
cloudify/workflows/tasks_graph.py
cloudify/workflows/workflow_api.py
cloudify/workflows/workflow_context.py

Rewrite the TasksGraph, and the WorkflowTasks themselves, to use callbacks
instead of polling task state.
This makes the graph execution faster and less resource-intensive, as well as
lower latency; also, the code is more readable (I hope!) as there's no more
things like multi-line conditions in `_executable_tasks`, no networkx graphs,
and less moving parts in the tasks themselves and the _TaskDispatcher.
Also some changes to the tests.
See each commit message for details.
BTW, @geokala, this WOULD be net -200 lines, it's only +60 because of the types.yaml! :P

RD-208 Replace tasks polling with callbacks

---

cloudify/plugins/lifecycle.py

graph.successors and .predecessors is not a thing anymore, and
tbh never should've been, because exposing the internal networkx
.graph was a always dumb idea.
Use the correct ._dependencies and ._dependents instead.
We'll consider making public methods for these, but not yet
This fixes the integration tests: integration_tests/tests/agentless_tests/test_depends_on_lifecycle_operation.py

workflow lifecycle dependencies: use the new taskgraph

---

cloudify/workflows/tasks.py

When the task gets finished, but we received a cancel request in
the meantime, just return the finish value.
Only throw ExecutionCancelled if we were cancelled and the task
has no return value (yet).
In other words, if the task finishes at the same time as the execution
gets cancelled, the task finish value gets priority. Because well,
it did finish.

WorkflowTaskResult.get: support cancel when task is already done

---

cloudify/workflows/tasks_graph.py

The superclass still needs to see the kwargs: at least the info
kwarg must be passed through, so that it can be stored/dumped.
Fixes `integration_tests/tests/agentless_tests/test_runtime_functions.py -k test_change_flag_update_resume`

SubgraphTask: pass kwargs to super

---

cloudify/workflows/tasks.py

The task is being duplicated, so we must copy these as well.

task duplicate: also duplicate success/failure handlers

---

cloudify/workflows/tasks.py

the original .apply_async() is called in workflow context, so
when it is delayed and called in a different thread - the timer thread-
it needs to be in wokrflow context as well.
We have the workflow context on the task, so let's just push it.

with_execute_after: push workflow context

---

jenkins/Jenkinsfile
setup.py

Py 2.6 doesn't support pyyaml 5.3.1. Therefore, specialcase it to keep 4.2.
The only place we still allow py 2.6 is the agent, and that does NOT
install the `.[dispatcher]` extra anyway. But we do want to be able to
still run unittests.

Bump pyyaml to 5.3.1

---

cloudify/rabbitmq_client.py

Yes we did change `self._target_host` every iteration.
However, that was formatted into the `url` only ONCE.
Now, format the whole url every iteration instead.

rabbitmq_client: re-compute the url on every try

---

script_runner/tests/test_ctx_wrapper.py

That test used to assert on the logs directly, but there can be
a "Waiting for process XXX to end" message, depending how long
did the process take to run.
That causes test_logger to fail randomly, especially on Jenkins.
Instead, just ignore messages that are unrelated to the test.

RD-1048 script_runner: ignore log messages unrelated to the test

---

cloudify/plugin_installer.py

This makes the uninstall task not set the "UNINSTALLING" state
at all (just deletes the plugin and then sets UNINSTALLED, or ERROR).
The reasons are:
1. If the set-state fails, we end up not deleting the plugin
directory. For some users this is a very fatal error (working
on a plugin and deleting/uploading the plugin often, you end up
keeping the old code)
2. The UNINSTALLING state is not very important because the plugin
stays in this state for only the very short amount of time that
it takes to delete a directory (if that fails, it goes to the
ERROR state anyway). In practice, the set-state is going to take
longer than the delete itself.
Taking those into account, the risk-of-fatal-error vs usefulness
suggests to just skip setting that state.

RD-1091 plugin_installer: skip setting the uninstalled state

---

cloudify/context.py
cloudify/utils.py
cloudify/workflows/workflow_context.py

Add one more operation context parameter (`workflow_parameter`).  The
parameter is a copy of workflow's parameters, except for the `ctx` key
(which is both not necessary, hard to serialize and maybe even risky).

RD-655 Propagate workflow parameters to executions

---

cloudify_rest_client/deployments.py

Note that "groups" already means the scaling groups in the
deployment.

RD-1158 Add .deployment_groups to the deployment restclient response

---

setup.py

This PR address the issue of `ssl` package where python 2.7.x earlier than 2.7.9 doesn't support ssl contexts which means we should check that and make all the python versions lower than 2.7.9 and also have 2.6 run the old pika instead which is 0.11.2 instead of running the latest one which is 1.1.0

RD-1345 Use pika 0.11.2 for python version < 2.7.9

---

cloudify/workflows/workflow_context.py

We sometimes get into this without a deployment id, for workflows
that arent system-wide but also aren't a deployment workflow
(eg. uploadt-blueprint)
In this case, don't fetch nodes, because there's nothing to fetch,
and trying with a null filter would just return all nodes
in the manager ever

RD-1333 workflow-ctx: if no deployment id, don't fetch nodes

---

dsl_parser/constants.py
dsl_parser/elements/blueprint.py
dsl_parser/elements/misc.py
dsl_parser/scan.py
dsl_parser/tests/test_labels.py

This PR handles adding `labels` to the DSL. Now, if you want to add labels to a deployment, you can do it straight from the blueprint itself by specifying them under `labels`. 
The labels' values are specified under the key `value`, so in the future, we will be able to add other keys to the `label` element (such as `description` or `constraints`).

RD-959 Add labels to DSL

---

cloudify/cluster.py

We retry fileserver downloads with other cluster nodes, because
filesystem replication is asynchronous.
However /blueprints/<id>/archive is also a fileserver download,
but it's gated behind restservice so that its 404s dont necessarily
have the headers we're looking for. And in principle I suppose
error messages don't need to have that header.
So, also look at the URL when deciding whether to retry. Can't think
of a better way.
(same for snapshots, but of course snapshots aren't as important,
because we're not really downloading them all that much; but
blueprints, we do, in the upload_blueprint workflow)

RD-1414 Cluster client: also retry /archive 404s

---

cloudify_rest_client/client.py
cloudify_rest_client/labels.py

This PR adds the rest-client mechanism for the `labels/blueprints` endpoint.
The complementary PR for the rest service is https://github.com/cloudify-cosmo/cloudify-manager/pull/2681

RD-1410 Add labels/blueprints endpoint

---

cloudify/cluster.py

In principle, any request to those, can touch the filesystem, so any
404 there should be retried with another node

RD-1414 Retry all 404 requests to blueprints/snapshots

---

cloudify/cluster.py

A 502 means restservice is down, there's no reason to treat it
differently than a connectionerror

RD-1471 Cluster client: also retry on a 502

---

dsl_parser/elements/misc.py
dsl_parser/tests/test_labels.py

- Changing `value` to `values` in the `blueprint_labels` section in the blueprint.
- Limiting the values to be of type `text_type` or dictionary.
Complementary PR https://github.com/cloudify-cosmo/cloudify-manager/pull/2701

RD-1507 Change value to values in blueprint_labels

---

cloudify_rest_client/deployment_updates.py
dsl_parser/tasks.py
dsl_parser/tests/test_inputs.py
dsl_parser/utils.py

* Inputs type casting functionality
In some rare (?) cases there might exist deployments with invalid type
of inputs (e.g. '20' stored where input type should be integer).  This
patch adds functionality to attempt to automatically cast types of input
values to expected (a.k.a. inputs auto-correction).
* Update rest_client to pass add_correct_types flag

CYBL-1107-Automatically fix inputs' types

---

cloudify_rest_client/node_instances.py
cloudify_rest_client/nodes.py

these methods need the deployment id, and it seems better to pass it
separately rather than have to put it in every single node

node/instances create_many: pass deployment_id separately

---

script_runner/tasks.py

Don't break on source files that are non-ascii.
Instead, just let's say they're utf-8.

RD-1560 script_plugin: handle non-ascii script source

---

dsl_parser/elements/deployment_schedules.py

The change is to allow complex weekdays such as _2mo_ for the 2nd monday of the month, or _l-fr_ for the last friday of the month  to pass validation at the DSL

RD-1397 Allow complex weekdays in DSL validation

---

dsl_parser/utils.py

Extend types auto-correction functionality to boolean type.  Map
strings: `"true"` to boolean `True` and `"false"` to `False`.

CYBL-1118 Automatically correct valid booleans

---

cloudify/models_states.py

This PR created in order to expose deployment statuses that can be used on rest side and also to be used in any other places required to do some checking on deployment statuses

RD-1480 Expose latest execution state for deployment

---

cloudify/models_states.py
cloudify_rest_client/deployments.py

This PR created in order to expose all the deployment statuses from the backend and it can be used on the client side to check all deployment statuses

RD-1482 Add deployment state to the deployment response

---

cloudify_rest_client/plugins_update.py

The purpose of this modification is to provide the administrator with a tool to reconcile the statuses of plugins updates according to statuses of relevant executions.
The new `reevaluate_active_statuses` flag in the `PluginsUpdateClient.update_plugins()` will force reevaluation of active plugins-updates' statuses based on following scheme:
```
execution status | new plugins_update status
------------------+---------------------------
terminated       | successful
failed           | failed
cancelled        | failed
cancelling       | failed
force_cancelling | failed
kill_cancelling  | failed
```

CYBL-1114 Reevaluate plugins update statuses

---

cloudify_rest_client/deployments.py

When creating new deployments via group, instead of providing just inputs,
allow providing a whole deployment dict, and new deployments will be based
off of that.
These dicts, which specify new deployments to be created, can contain
so far just the key "inputs", but later in RD-1655 we'll also allow providing
things like the id, deployment_settings, labels, etc

RD-1655 depgroup create: allow providing more than just inputs

---

cloudify_rest_client/deployments.py

Allow providing more than just `inputs`.

RD-1655 dep-groups: create new deployments: allow id, labels

---

cloudify_rest_client/execution_schedules.py

Take the weekdays as a list of weekdays, instead of a comma-separated
string, because structured data is of course better than just strings.
It would be good if the parsing was done at the edges of the system
instead of in the middle like here

RD-1603 schedules rest-client: take weekdays as a list

---

cloudify/tests/test_utils.py
cloudify/utils.py

Adding a "month" timedelta is not that easy! We'd like to have used
dateutil.relativedelta here, but we don't have dateutil in here, and
I don't want to pull it in for just this.
Just doing .replace(month=month+delta) isn't enough, because for
some values that's a ValueError: eg. you can't add 1month to
March 31st this way, because that would end up being April 31st, and
that doesn't exist.
Instead, .replace the month for a datetime with day=1
(so Mar31 -> Apr01) and then add the original number of days as a
timedelta, which does carry over the month
(so Apr01 + 30 days -> Apr31 -> May01).

Parse datetime utils: handle shorter months

---

cloudify_rest_client/exceptions.py

Add new exception type when invalid csys is passed which could be parent that does not exist or invalid in format when validating the deployment parent

RD-1484 Add invalid csys environment input exception

---

cloudify/deployment_dependencies.py
cloudify_rest_client/inter_deployment_dependencies.py

Add target_deployment_func in create_deployment_dependencies
Until today the inter-deployment dependencies REST client did not handle
target_deployment_func.  As we plan on using it instead of a direct DB
access when creating inter-deployment dependencies, it's a must-have.

RD-1602 Async inter deployment dependencies

---

cloudify_rest_client/deployments.py

the server will not take kindly to creating an arbitrary amount
of deployments in a single call. Allow the client to automatically
batch creations.
batch size of 5000 by default should be still fast enough to
be created on any machine

client.dep_groups.add_deployments: add a batch_size

---

dsl_parser/functions.py
dsl_parser/tests/abstract_test_parser.py
dsl_parser/tests/minimal_types.yaml
dsl_parser/tests/namespace/test_functions.py
dsl_parser/tests/namespace/test_general_namespace.py
dsl_parser/tests/namespace/test_relationships.py
dsl_parser/tests/test_blueprint_import.py
dsl_parser/tests/test_cloudify_basic_types_mark.py
dsl_parser/tests/test_functions.py
dsl_parser/tests/test_get_capability.py
dsl_parser/tests/test_get_secret.py
dsl_parser/tests/test_labels.py
dsl_parser/tests/test_outputs.py
dsl_parser/tests/test_register_function.py
dsl_parser/tests/test_relationships_overloading.py
dsl_parser/tests/utils.py

`get_group_capability` is a new intrinsic function that gets 
capabilities of all deployments in a deployments group.
That logic is... mostly not here. Similar to other intrinsic
functions (eg. `get_capability`), this side only returns whatever
it received from the storage backend, so the interesting part
is going to be there (ie. in c-manager).
So this is mostly boring and trivial.
However... I have sweetened the deal (pray I don't alter it any
further!), and the commits leading up to the actual implementation
refactor some of the tests, and simplify functions.py just a bit.
The results aren't half bad!

RD-1165 Add get_group_capability

---

cloudify/workflows/local.py
dsl_parser/functions.py
dsl_parser/tests/abstract_test_parser.py
dsl_parser/tests/test_get_environment_capability.py

Add support to use new intrinsic function `get_environment_capability` which is an alias for using `{ get_capabilities : [ {get_label : csys-obj-parent,0}, CAPABILITY_NAME]}`

RD-1958 Add get_environment_capability function

---

jenkins/Jenkinsfile
setup.py

This is an attempt to maintain ability to run the tests for Python 2.6 even when the support for that software will be non-existent.
https://github.com/pypa/pypi-support/issues/978

RD-2111 Python 2.6 environment workaround

---

cloudify_rest_client/deployments.py

Not only pre-existing filter can be used to filter the deployments to be
added/removed from the deployments group (`filter_id`), but also a list
of `filter_rules` can be now be applied.

RD-2263 filter_rules to add/remove deployments from the group

---

cloudify/dispatch.py
cloudify/tests/test_dispatch.py

I don't know why was this request retried. No other request is
retried like this.
All this does, is makes a 401 get displayed multiple times,
and in case a 500 happens, it will be hidden by the additional 401s.
This dates back to CFY-1599, which was related to cancelling, but
I dont see how this specifically relates. Anyway, CFY-1599 didn't
really solve the cancel-in-pending issue, only by the time we
introduced kill-cancels that was really fixed.

RD-2288 Remove useless retries

---

dsl_parser/elements/operation.py

Switched the "if file" branch to run before the "if plugin" branch, so that when we have scripts with a path "script.py" or "script.sh", we won't parse it as the script plugin (same goes for scripts with other accidental plugin names)

RD-2015 Fix bug with script filenames of thew form 'script.*'

---

dsl_parser/elements/operation.py

if `_is_remote_script_resource(operation_mapping, remote_resources_namespaces)` returns true, but we actually have a plugin to run the operation, we don't want to default to script plugin running it, but instead it should continue to the other branch, under `if candidate_plugins`

RD-2015 Fix condition in for namespaced workflows

---

cloudify/manager.py
cloudify/tests/test_context.py

This reverts commit bc0de25a7ac962fb75337a7234c08d58d648155a.
Turns out sourcing files from the deployment's directory (e.g.
http://...//resources/deployments/default_tenant/dep/file.txt) is a
feature we shouldn't break.

Revert "RD-2316 Look for the resources in update_blueprint path (#774)"

---

cloudify/plugin_installer.py

This ports #782 to 6.0.0
The plugin representation contains the error, so don't put it in
errors, otherwise we get the error in the error, and that quickly
leads to the string getting jsonified (and escaped) fifty times

RD-2383 Avoid printing out the plugin dict, in plugin installation errors

---

dsl_parser/scan.py

blueprints restored from pre-6.0 snapshots won't necessarily have
that field, but still need to be able to be scanned, when creating
new deployments from them. Don't throw a KeyError if the value isn't
there.

RD-2375 dsl-parser: cope with missing deployment_settings

---

cloudify/endpoint.py

This is probably only used in tests

Fill `managerment_host` for LocalEndpoint.get_brokers()

---

cloudify/workflows/tasks.py
cloudify_rest_client/node_instances.py

We used to first fetch the instance, to figure out the current
version, and then set the new state anyway.
So, the only reason we fetched it, was so that our update always
succeeds - we didn't react to the received state in any way.
We can simply just cut out the middleman, and force-set the
state directly, without fetching it.
And anyway, force-setting, like we (essentially) did before,
and do now, does make sense for the state - instance state is never
changed concurrently, only runtime-properties are (and that's what
version is for).

RD-2579 _SetNodeInstanceStateTask: force-set the state

---

cloudify/amqp_client.py
cloudify/dispatch.py
cloudify/tests/test_dispatch.py
cloudify/workflows/tasks.py
cloudify/workflows/workflow_context.py

Instead of making a queue+amqp connection per task, make
only one for the whole execution.
Also some simplifications around.

RD-513 Use a single AMQP queue per execution

---

cloudify/workflows/workflow_context.py

of course, if the client is already in the cache, we do need to
retrieve it :)

Fixup TaskDispatcher.get_client

---

cloudify/context.py

we used to do that in the separate figuring-out-the-prefix method,
now we use the property instead, so let's have the property behave
the same way.

plugin.prefix: fall back to name if package_name is empty

---

cloudify/plugin_installer.py

no point having pip check for upgrades in this. It just makes
things slower (especially if there's no internet access)

plugin_installer: run pip with --disable-pip-version-check

---

cloudify/workflows/tasks.py
cloudify/workflows/workflow_context.py

The actual values are going to be stored in self.kwargs, and
serialized into s['task_kwargs'] directly, without the additional
dict

Builtin tasks: strip a layer of .task_kwargs

---

cloudify/logs.py

the `_send_event` function used to get a string to select which
kind of "context" to use, and then created it
instead, just pass in the "context" directly. It's mostly the same
logic but makes it shorter and drops an argument
(and next, we'll also drop `ctx` from it as well)

logs.py: drop an `if` ladder

---

cloudify/workflows/tasks_graph.py

For the tasks to be restored, their name needs to be pointed back
to the actual class.
This fixes all the test_resume inte-tests

Allow restoring builtin tasks

---

cloudify/dispatch.py

when the execution state is changed to cancelled, we can't send
events anymore. The event needs to be sent BEFORE the execution
is actually cancelled. Otherwise we just get 401s on the attempt
to try and send the event.

dispatch: send cancelled event before setting the status

---

cloudify/workflows/workflow_context.py

.handler just doesnt exist. It's .internal.handler. Whoops.

CloudifySystemWideWorkflowContext: use handler correctly

---

cloudify/workflows/tasks.py

We used to set it, and we assert on it in some tests, so why
not - let's keep the old interface, and still set .info
this fixes a few tests in `integration_tests/tests/agentless_tests/test_depends_on_lifecycle_operation.py`

builtin tasks: set .info as well

---

cloudify/workflows/workflow_context.py

it might be a float, not an integer, but let's int() it so that it displays nicely
in 6.1+ it's not a float anymore, since cloudify-cosmo/cloudify-manager#3047

get_task_configuration: int() the retries count

---

cloudify/workflows/workflow_context.py

See the docstring of `_task_deletes_exchange` for explanation.
As always, cache invalidation is one of the Hard™ things!
We clear the whole cache because that is trivially correct: otherwise,
it'd be hard to figure out what exchange should we even remove from
the cache, because the delete task is a mgmtworker task (and so,
target = `cloudify.management`), on the `/` (not tenant) vhost - and
so, separate Handler instances. And the exchange/queue names aren't
necessarily the same as the node-instance name, because of proxied
agents.

RD-2679 Clear the queue-bind cache when deleting agents

---

cloudify/logs.py
cloudify/utils.py
cloudify_rest_client/events.py

Turns out it's not always the case that we only create events/logs
via a request authenticated by an execution token - when running hooks,
we are authenticated by the user's rest token instead.
So, allow passing in the execution id, so that requests authenticated
by a rest token, know which execution are they related to.

RD-2751 Attach the execution id to the events/logs create

---

cloudify/dispatch.py

Hooks are sent by the restservice since cloudify-cosmo/cloudify-manager#3156
No need to do it here.

RD-2751 Workflow events: don't send hooks

---

cloudify/workflows/tasks.py

Some tests depend on there being a "SENDING" state/event stored.
Well, let's bring it back for compat. I didn't really want to do that, but alas.
This fixes eg. `integration_tests/tests/agentless_tests/test_events.py::EventsTest::test_search_event_message`

RemoteWorkflowTask: bring back the 'sending' state

---

cloudify/workflows/workflow_context.py

well if we str() the exception and then getattr causes, then obviously
the causes is None, because we're getattr-ing off of the string!
instead, let's getattr from the actual exception.
I could've just as well simply reversed the order of the two lines,
but this seems better

update_operation: pass through exception_causes

---

cloudify_rest_client/deployment_updates.py

We drop support for a deployment update based on a blueprint uploaded
in the POST data.  Instead user should rely on already uploaded
blueprint (`cfy deployments update -b BLUEPRINT_ID`).

RD-2616 Drop the old code for deployment update

---

dsl_parser/constants.py
dsl_parser/elements/inputs.py
dsl_parser/tests/test_inputs.py

It is a simple string that will be used in UI instead of a input name.
Blueprint snippet:
```yaml
inputs:
aws_access_key_id:
type: string
display_label: AWS Access Key ID
default: { get_secret: aws_access_key_id }
```

RD-2800 Add a display_label input property

---

cloudify/workflows/events.py
cloudify/workflows/tasks.py

Let's make events consistent between dry-run and normal executions:
both will now emit events for subgraphs. And every task event for dry-run
will now say it's a dry-run.

RD-2891 Dry-run node events & subgraph events

---

cloudify/workflows/tasks.py
test-requirements.txt

It used to be set in the `else` branch but not in the "retry" branch.
Whoops :)

RD-2948 Make ctx.operation.retry honor its retry_after

---

cloudify/tests/test_tasks_graph.py
cloudify/workflows/tasks_graph.py

The point is checking that the resumed-install delete actually works at all;
but also, I wanted to figure out a way to test the graphs at all.
So in the future we'll hopefully add more!

RD-2969 Add a few tests for workflow graphs

---

cloudify/tests/test_tasks_graph.py
cloudify/workflows/tasks_graph.py

WorkflowTasks that come from modules other than cloudify-common
itself (eg. plugins!), can now be restored. All they need to do is
to declare task_type accordingly

RD-3000 When restoring tasks, allow importing custom types

---

dsl_parser/elements/inputs.py
dsl_parser/tests/test_inputs.py

The blueprint's input `required` is True unless directly specified
otherwise.  This is making blueprint validation consistent with
deployment create.

RD-3012 Make the required flag True by default

---

cloudify_rest_client/deployment_updates.py

Just pass everything through. The endpoint is somewhat internal anyway.

Allow other params when creating dep-updates

---

dsl_parser/tests/namespace/test_workflows.py

In a non-r'' string, you want `\\w`, not `\w`. Just `\w` is still two characters,
(backslash, w), but emits a warning.

dsl-parser test_workflows: proper escape sequence

---

cloudify/workflows/workflow_context.py

It doesn't make sense to only download new instances but not nodes,
because the new instances could be for nodes that we haven't seen
yet!

RD-3085 When refreshing node-instances, also refresh nodes

---

.circleci/config.yml
jenkins/Jenkinsfile
jenkins/build-pod.yaml

We don't build anything for py2.6 any more since pip got unhappy,
so let's not test on it.

Remove python 2.6 tests

---

dsl_parser/tests/abstract_test_parser.py
dsl_parser/tests/interfaces/test_interfaces_merger.py
dsl_parser/tests/interfaces/test_interfaces_parser.py
dsl_parser/tests/interfaces/test_operation_merger.py
dsl_parser/tests/namespace/test_functions.py
dsl_parser/tests/namespace/test_node_templates.py
dsl_parser/tests/namespace/test_plugins.py
dsl_parser/tests/namespace/test_relationships.py
dsl_parser/tests/namespace/test_workflows.py
dsl_parser/tests/scaling/test_multi_instance.py
dsl_parser/tests/scaling/test_scaling_policies_and_groups.py
dsl_parser/tests/test_blueprint_import.py
dsl_parser/tests/test_constraints.py
dsl_parser/tests/test_deafult_import_resolver.py
dsl_parser/tests/test_framework_parser.py
dsl_parser/tests/test_functions.py
dsl_parser/tests/test_get_attributes_dict.py
dsl_parser/tests/test_get_attributes_list.py
dsl_parser/tests/test_import_resolver.py
dsl_parser/tests/test_inputs.py
dsl_parser/tests/test_parser_api.py
dsl_parser/tests/test_parser_logic_exceptions.py
dsl_parser/tests/test_plugins_to_install.py
dsl_parser/tests/test_relationships.py
dsl_parser/tests/test_relationships_overloading.py
dsl_parser/tests/test_yaml_anchors.py

This converts all teststools stuff into unittest stuff.
(pytest-way, if we want, can come later)
Those are mostly bulk changes, so look at each commit separately.

RD-3115 dsl-parser tests: stop using testtools

---

dsl_parser/rel_graph.py

Node instances which have two or more relationships to the same target
failed to update because only one of these relationships is stored for
the `node_instance` in DB.  This patch provides a fail-over mechanism
for such cases and build relationships information based on a relevant
node's relationships.

RD-3125 Retrieve relationship from node

---

cloudify/workflows/workflow_context.py

The new dep-update uses this, so just expose this as an attribute.
This fixes the NewTestDeploymentUpdateAddition::test_add_relationship
inte-test

CloudifyWorkflowRelationship: expose .type

---

cloudify/dispatch.py

This is not perfect yet, because the traceback could be better.
But have _some_ traceback, at all

RD-3095 Include a traceback in the "workflow failed" message

---

cloudify/dispatch.py
cloudify/workflows/workflow_context.py

...not based on the prior state. We set that flag explicitly, so let's
use it, instead of basing this on some additional thing (in this case,
the execution state)

RD-3221 Workflow is resumed based on the .resume flag

---

cloudify_rest_client/deployments.py

It's a feature that we have, and that I want to use, give me the
param.

RD-3228 restclient: expose the async_create flag in client.deps.create

---

dsl_parser/functions.py
dsl_parser/tests/test_functions.py
dsl_parser/tests/test_get_attribute.py

For both get_property and get_attribute. See commit messages.

RD-3229 allow changing context when evaluating functions

---

cloudify/workflows/workflow_context.py

we don't set it "if at the beginning..." blabla. We now just set it
as passed-in from the restservice. (since #886)

workflow_ctx.resume: remove invalid comment

---

cloudify/tests/test_operation_retry.py

no reason to just sleep for 3 seconds. The tests themselves do pass
`task_retry_interval=0`, but #845 made it so that the retry_after
passed into ctx.operation.retry() is actually not ignored. So it
made tests just sleep for no reason. So let's not.

test_operation_retry: don't wait 3 seconds in the test

---

setup.py

This is required since aiohttp 3.8.0 handles type hinting more strictly:
https://github.com/aio-libs/aiohttp/pull/5267/files
which leads to the following error:
```
> `
> [2021-11-01T08:31:48.662Z]     import aiohttp
> [2021-11-01T08:31:48.662Z] py3env/lib/python3.6/site-packages/aiohttp/__init__.py:6: in <module>
> [2021-11-01T08:31:48.662Z]     from .client import (
> [2021-11-01T08:31:48.662Z] py3env/lib/python3.6/site-packages/aiohttp/client.py:36: in <module>
> [2021-11-01T08:31:48.662Z]     from . import hdrs, http, payload
> [2021-11-01T08:31:48.662Z] py3env/lib/python3.6/site-packages/aiohttp/http.py:7: in <module>
> [2021-11-01T08:31:48.662Z]     from .http_parser import (
> [2021-11-01T08:31:48.662Z] py3env/lib/python3.6/site-packages/aiohttp/http_parser.py:41: in <module>
> …
```

Pin aiothhp==3.7.4.post0

---

cloudify/workflows/workflow_context.py

Relationships in principle shouldn't be None, but if they happen to
be inserted like that, don't just break in a weird place in the
code, just treat it as nonexistent.

RD-3272 workflow-ctx: don't break on None relationships

---

cloudify/utils.py

This goes to a patch since it affects anyone who use the execution scheduler and provide a since/until in "+n months", and the resulting month happens to be December

Fix incorrect handling of month==0

---

cloudify_rest_client/client.py

API-service error responses contain `detail` rather than `message`

RESTclient: don't break on missing `message` in an error message

---

cloudify_rest_client/execution_schedules.py

We allow changing everything, why not the workflow_id as well!

RD-2614 Exec-schedules update: allow changing workflow_id

---

cloudify/context.py
cloudify/workflows/workflow_context.py

Make two more attributes available in the workflow context:
* `ctx.deployment.display_name`,
* `ctx.deployment.creator`.

RD-3435 More deployment details in context

---

cloudify/utils.py
script_runner/tasks.py

Since 6.2, ctx.logger requires a context to even be able to log.
So let's pass it. OutputConsumer will now take a ctx, but it will be
optional, because in principle other loggers, non-ctx ones, can also
be used with it.

RD-3721 script_plugin: propagate stdout/stderr

---

dsl_parser/functions.py
dsl_parser/tests/test_functions.py

... it's basically to let string_lower and string_upper opearte on other
intrinsic functions like:
```
string_lower: { get_property: [x, some_string] }
```

RD-3559 Allow inputs other than string for string_{lower,upper}

---

cloudify_rest_client/node_instances.py

This is going to be used internally, to set system-properties, from
the mgmtworker. There's nothing stopping a user from using it as well,
if they truly want to break their stuff.

RD-3673 Add system_properties to ni.update()

---

cloudify/plugins/workflows.py
cloudify/tests/resources/blueprints/minimal_types.yaml
cloudify/tests/resources/blueprints/test-check-status.yaml
cloudify/tests/test_builtin_workflows.py
cloudify/workflows/local.py
cloudify/workflows/tasks_graph.py
cloudify/workflows/workflow_context.py
cloudify_rest_client/node_instances.py

The workflow is simple enough, but do see commits separately.
Anyway, it's very similar to execute_operation, but it will only run
the one specific task, and it will also store the results in
system_properties.
For now, the results are just the boolean "ok". We'll be adding more
data in there soon.

RD-3675 Add the check_status workflow

---

cloudify/context.py
cloudify/tests/resources/blueprints/relationship_context.yaml
cloudify/tests/test_ctx_relationships.py
cloudify/workflows/workflow_context.py

The parameter is set for relationships and is either 'target' or
'source'.

RD-3739 Add ctx.operation.relationship to the context

---

cloudify/workflows/workflow_context.py

None is an invalid default, because the restservice checks the type.

RD-3675 Default version to 0

---

cloudify_rest_client/node_instances.py

Just declare that field. It exists, no reason not to expose it on the
rest client objects.

rest-client: declare ni.system_properties

---

cloudify/plugins/workflows.py
cloudify/tests/test_builtin_workflows.py
cloudify/workflows/workflow_context.py

This puts the following in system_properties['status']:
```python
{
'ok': task.get_state() == TASK_SUCCEEDED,
'timestamp': datetime.utcnow().isoformat(),
'task': task.name,
'result': task.async_result.result
}
```
more to be added as needed

RD-3675 Add more info to the check_status result

---

cloudify/_compat.py
cloudify/test_utils/__init__.py
cloudify/tests/test_local_workflows.py
cloudify/workflows/local.py

This adds deployments for local workflows.
This isn't all that's needed, but without having the concept
of deployments at all, we can't really progress much.
This is in a backwards-compatible fashion, where the local
workflow tests, are going to just create a blueprint AND
a deployment, of the same name, in place of just creating
a blueprint.

RD-3900 Add the concept of deployments to local workflows

---

cloudify/workflows/workflow_context.py

Those are all the calls that are used by dep-update. Currently, the
workflow uses the rest-client directly for them. But I want it to
use the workflow-context, because then, we can also (later) implement
a local-handler for it, and test/use dep-update in local workflows
as well.
This PR is mostly very boring, because all it does, is exposes all
the missing stuf on workflow_ctx.

RD-3859 Add workflow_ctx interface for dep-update related calls

---

cloudify/tests/test_task_serialize.py
cloudify/workflows/tasks.py
cloudify/workflows/tasks_graph.py
cloudify/workflows/workflow_context.py

Local workflows don't store operation, so they shouldn't mark
operations as stored.
If operations are flagged as stored, then they don't emit state-update
events (because the restservice automatically inserts those events)

RD-4035 Only mark operations as stored, if they were really stored

---

cloudify/plugins/workflows.py
cloudify/tests/test_builtin_workflows.py

Normally, blueprints are going to use the builtin update workflow
(the one in cloudify_system_workflows);  but old (6.2 and earlier)
blueprints still have the update workflow defined in the yaml, and
those point to this function;  so, let's make this function just call
the builtin one.
Also, remove those tests, because this workflow doesn't live here
anymore.

RD-4096 Update: delegate to the new workflow

---

cloudify/workflows/workflow_context.py
cloudify_rest_client/node_instances.py

Similar to deleting nodes, dep-update needs to be able to delete
node-instances as well, going through the wctx.
This only implements deleting instances on the manager - for now.
The `cfy local` counterpart is TBD.

RD-2617 An interface for deleting node-instances

---

setup.py

revert pin aiohttp to latest py3.6 supporting version
See here: https://github.com/cloudify-cosmo/cloudify-common/pull/905
aiohttp 3.8.1 hasn't fixed the Deque import issue yet (fixed in not-yet-released 3.9), so they basically don't support Python 3.6 currently

revert pin aiohttp

---

setup.py

Requests 2.26+ drops support for python 3.5, making our ubuntu 16 agent build fail

Pin requests to 2.25 for python 3.5

---

cloudify/workflows/workflow_context.py

This obviously fails snapshot tests, otherwise.
Anyway, if the tags are empty, might as well skip the evaluation.
Why waste the rest call?

RD-4131 Skip resource_tags evaluation when they're empty

---

cloudify_rest_client/inter_deployment_dependencies.py
dsl_parser/constants.py
dsl_parser/constraints.py
dsl_parser/tasks.py
dsl_parser/tests/namespace/test_functions.py
dsl_parser/tests/test_get_secret.py
dsl_parser/tests/test_inputs.py
dsl_parser/tests/test_outputs.py
dsl_parser/tests/test_register_function.py
dsl_parser/utils.py

The new data type `deployment_id` refers to deployments existing in the
system.  A valid input of that type is going to guarantee that given
deployment exists (possibly for a different tenant though).
Moreover a new `filter` constraints is added which might enforce
deployments to be associated with given tenants, have specific labels
or have display_names follow some pattern.

RD-4115, RD-4116, RD-4282 `deployment_id` data type

---

cloudify/workflows/local.py

This is a WeakValueDict! 2-step access like `if not in d` + `d[]`
can fail, because the value might get evicted between those calls.
And yes, I've seen it happen.
Instead, only one `.get`

local workflows: threadsafe access to _instance_locks

---

cloudify_rest_client/blueprints.py

This will be required for snapshot restore

Support skipping exec on blueprint.publish_archive

---

cloudify_rest_client/operations.py

The name is not required anymore

RD-4328 Allow filtering graphs by just execution-id

---

cloudify_rest_client/node_instances.py

In #954, we added `system_properties` to right after `runtime_properties`,
but that breaks compat with usage that passes all arguments positionally.
Instead, let's put it at the end.

REST-client: ni.update() - keep back-compat wrt. args ordering

---

cloudify_rest_client/plugins_update.py

Added `deployments_per_tenant` and `tenant_name` properties.  It's going
to be useful e.g. in cloudify-manager tests.

RD-4373 Extend PluginsUpdate wrapper class

---

cloudify/dispatch.py

Well this needs to go under all the `except`s, same as the regular
func call.
FWIW this is about workflows that create operations but not in the
context of a graph.
As in, yes, it is allowed to do, like
```python
def workflow(ctx):
instance = ctx.node_instances[0]
instance.execute_operation('foo.bar')
```
And that operation WILL be awaited-for, in just these lines I'm moving.
So let's handle errors in them.

RD-4623 Non-graph execs: handle errors same as graph execs

---

dsl_parser/functions.py
dsl_parser/tests/test_get_attribute.py

Instead of substituting evaluated values with possibly another level of
intrinsic functions (and mistakenly breaking the indexation), let's
evaluate intrinsic functions "da capo al fine" (until we get actual
values).

RD-4280 Keep evaluating functions until got result

---

cloudify_rest_client/deployments.py

It's not always deployments come with `ID` already set, let's use
`self.id` getter then and circumvent the problem.
Also that should not cause any harm as `DeploymentScalingGroup`s do not
require a non-null `deployment_id`.

Stay on the safe side creating `DeploymentScalingGroup`s

---

dsl_parser/constraints.py

In case a `deployment_id` can be retrieved from the context (e.g. when
running a workflow on a given deployment), don't require it to be
present in the constraints for data-based data types which require
`deployment_id` constraint.

RD-4711 Allow default `deployment_id` value for workflow parameters

---

dsl_parser/elements/imports.py
dsl_parser/tests/test_parser_logic_exceptions.py

Allow importing files which use earlier version of DSL than the
blueprint.  One can use `cloudify_dsl_1_3` types.yaml in
a `cloudify_dsl_1_4` blueprint.

RD-4788 Allow import of earlier DSL versions

---

cloudify/endpoint.py

We can't short-circuit to just `return resource`, it needs to keep
the (bytestring) type. This function is a bit whack tbh. But this
way works.
This fixes the inte-test `test_get_and_download_deployment_resource`
in `integration_tests/tests/agentless_tests/test_deployment_resource.py`

_render_resource_if_needed: return a bytestring

---

cloudify_rest_client/node_instances.py
cloudify_rest_client/nodes.py

Drifted/status-unavailable flags for node-instances and nodes.

RD-4612 restclient: drift/status flags

---

dsl_parser/tests/test_parser_api.py
dsl_parser/utils.py

... because some plugins don't.
https://cloudifysource.atlassian.net/browse/RD-429?focusedCommentId=76279

RD-429 Do not require `resource_id` for external resources

---

dsl_parser/elements/imports.py
dsl_parser/tests/test_parser_api.py

A shallow merge of workflow settings. Allows overriding availability,
most notably. But also other things!
Before, attempting to override a workflow used to be just an error

RD-4617 Allow overriding workflows

---

cloudify_rest_client/deployments.py
cloudify_rest_client/nodes.py

Also, the _instance_counts param is no longer necessary

RD-4408 Declare instance drift/status counts on deployment

---

cloudify/utils.py

This will allow using a different dir than the env for cfy local
(in practice, the profile dir).
Passing stuff by environ is kinda stupid, but it's the least invasive
way of doing it for now.

Allow overriding plugins base dir

---

dsl_parser/models.py

It's not longer just a dict! This allows creating a plan from `{}`
and the structure will be there.

dsl-parser: default Plan with an empty schema

---

cloudify/workflows/workflow_context.py

- the repr is just nice, duh
- NodeInstance is already put into sets, so it very much SHOULD have
a hash+eq. It doesn't currently, which makes it break when some
instances are from before a `wctx.refresh_node_instances()` and
some are from after (then they compare not equal, which is... less
than useful)

Add a few magic methods to CloudifyWorkflowNode/Instance

---

cloudify/plugins/lifecycle.py
cloudify/plugins/workflows.py
cloudify/tests/resources/blueprints/minimal_types.yaml
cloudify/tests/resources/blueprints/test-heal-operation.yaml
cloudify/tests/test_builtin_workflows.py
cloudify/workflows/tasks_graph.py

This implements the new heal workflow, which will delegate to the
heal operations, and only fall back to reinstalling.
Nodes who do not declare the heal operation are just reinstalled
(keeping the old behaviour), so the new approach is opt-in.
To do this:
1. Implement a LifecycleProcessor front - we already use that for
installation etc, it's a convenient way to have dependencies already
set up for us
2. Add a whole bunch of `if`s and filtering to the workflow itself!
See the tests for specifics and details on the new behaviour.

RD-4465 Next-gen heal workflow

---

dsl_parser/elements/misc.py
dsl_parser/tests/test_resource_tags.py

Because we introduced them in Cloudify 6.2.x (so it's mostly BC)

RD-5218 Allow the `resource_tags` in DSL 1.3

---

dsl_parser/import_resolver/default_import_resolver.py
dsl_parser/tests/test_deafult_import_resolver.py

In case `dsl_version` was provided but `*{dsl_version}.yaml` does not
exist, default to the first `*.yaml` file which does not match
`*_\d_\d+.yaml` pattern.

RD-5217 Modify how plugin.yaml-s are looked up

---

cloudify/plugins/lifecycle.py
cloudify/tests/resources/blueprints/test-update-operation.yaml
cloudify/tests/test_builtin_workflows.py
cloudify/workflows/workflow_context.py

The update subgraph now examines the drifts, and not only runs our
own operations, but also relationship operations as well

RD-4466 dep-update: also run relationship operations

---

cloudify/plugins/workflows.py
cloudify/tests/test_builtin_workflows.py

Heal now has two modes of operation: if we do target a single instance,
then it is assumed to be unhealthy unless proven otherwise (this is
back-compat with pre-6.4).
And if we don't target an instance, but run heal on the whole
deployment, then nodes are considered healthy, unless proven failing.
This is so that we don't blindly run heal (or reinstall) on all nodes.
Also update the test to work that way: only node2 and node8_contained,
in that blueprint, are explicitly failing. Others, eg. node1, don't
even have a check_status defined, so there's no need to heal them.

RD-5091 Heal: default healthy/unhealthy based on how it was called

---

cloudify/plugins/lifecycle.py
cloudify/tests/test_tasks_graph.py
cloudify/workflows/tasks_graph.py

Adding an optimize method to the tasks graph, which will remove all
the empty tasks from the graph.
Currently, let's only run this optimization in the "lifecycle"
workflows. Users are free to run it as they see fit.
Also, in the future, we might come up with more "optimizations".
This impl. right now is pretty straightforward, but feel free to later
rewrite it as something more complex.

RD-5109 Remove unnecessary stub subgraphs

---

cloudify_rest_client/responses.py
cloudify_rest_client/tests/test_responses.py

Inspired by sqlalchemy. I find that we often do response[0], but this
is better in that there's no way to forget the check.

Add ListResponse.one()

---

cloudify/manager.py
cloudify/tests/test_node_state.py
cloudify/workflows/tasks.py
cloudify/workflows/tasks_graph.py
dsl_parser/tests/test_data_types.py

Errors thrown inside apply_async itself (such as "agent missing")
used to be just hidden. Now, let's show them.

RD-5505 Show apply_async errors in workflow tracebacks

---

cloudify_rest_client/exceptions.py
cloudify_rest_client/tests/test_exceptions.py

This way we get slightly more informative, but not too verbose, `CloudifyClientError`s

RD-5232 Print the server-side cause of `CloudifyClientError`

---

dsl_parser/import_resolver/default_import_resolver.py

re.match matches at the beginning of the string! Attempting to match
something at the end is futile. That's what we have `re.search` for.

RD-5524 Plugin resolver: use re.search, not re.match

---

dsl_parser/import_resolver/default_import_resolver.py

This fixes broken `manager_rest.test.infrastructure.test_resolver_with_catalog_support.TestPluginParseWithResolver testMethod=test_fetch_plugin_yaml_matching_dsl_version` test and also `Resolver.fetch_import` for plugins in general in case `dsl_version` is not provided.
This scenario (unknown `dsl_version`) should rather not happen in real-life scenario.

RD-5599 Return the "latest" plugin*.yaml in case dsl_version is not provided

---

cloudify/ctx_wrappers/ctx-py.py
cloudify/proxy/server.py
setup.py

- bump jinja2 version
- correct import path for the collections ABCs
(both 3.6 and 3.10 compatible)

RD-5674 Python 3.10 compatibility

---

cloudify/plugin_installer.py

Use the stdlib one instead. Nice!
Those flags don't exist with venv, they're just the default (with venv, you can just add `--upgrade`).

RD-5883 Plugin installer: replace virtualenv with venv

---

dsl_parser/constraints.py
dsl_parser/elements/inputs.py
dsl_parser/framework/elements.py
dsl_parser/tests/test_inputs.py

The new `error_message` constraints attribute is used for describing
a constraint-not-met exception.
Example:
```yaml
inputs:
location:
type: string
display_label: Location
default: https://github.com/cloudify-community/tf-source/archive/refs/heads/main.zip
constraints:
- pattern: ^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$
error_message: The value must be a URL.  The Url must start with http or https
percent:
type: integer
constraints:
- greater_or_equal: 0
error_message: The value must be greater or equal to 0
- less_than: 100
error_message: The value must be less than 100
```
---
Requires `>=cloudify_dsl_1_5`.

RD-6152 Constraints `error_message` attribute

---

setup.py

No need to pin this to a very specific version. Let's trust that aiohttp maintains semver compat,
Meanwhile, 3.8.1 is incompatible with python 3.11.

Relax aiohttp requirement

---

cloudify/plugins/workflows.py
cloudify/test_utils/local_workflow_decorator.py
cloudify/tests/resources/blueprints/minimal_types.yaml
cloudify/tests/test_builtin_workflows.py
cloudify/tests/test_context.py

In the install workflow, expose parameters that allow installing only a subset of a deployment. This is the same method we use in `execute_operation` (and so, `start`, `stop`, ...).
Also some test utils improvement first, so I recommend reading commits separately.

RD-6285 install: allow filtering node-instances 

---

cloudify/plugins/workflows.py
cloudify/tests/resources/blueprints/minimal_types.yaml
cloudify/tests/test_builtin_workflows.py

Now that `heal` is much more complex, there's no longer a simple way to "reinstall". We have the `LifecycleProcessor` method right there, all we need to do is to expose it.

RD-6287 Declare a `reinstall` workflow

---

dsl_parser/constraints.py

Apparently the UI team really wants for there to be a full stop there.

Constraint error message: re-add `.`

---

cloudify_rest_client/inter_deployment_dependencies.py
dsl_parser/functions.py
dsl_parser/scan.py
dsl_parser/tasks.py
dsl_parser/tests/test_get_capability.py

When computing IDDs, it's not enough to just return the function representation, because to evaluate that function later, we also need the context!
That is because e.g. `{get_capability: [dep1, {get_attribute: [SELF, x]}]}` depends on SELF, so we need to know the node instance id in order to evaluate that.
So, in this PR, we make sure to return IDDs in a new format: instead of the old:
```python
{
'nodes.n1.properties.xxx': {'get_capability': ['dep1', 'x']},
'nodes.n2.properties.yyy': {'get_capability': ['dep2', 'y']}
}
```
we will now be returning IDDs in the deployment plan in the format of:
```python
[
{
'function_identifier': 'nodes.n1.properties.xxx',
'target_deployment': {'get_capability': ['dep1', 'x']},
'context': {
'SELF': 'n1_abcdef',
}
}
]
```
In order to do this,
1. Rewrite …

RD-5953 Return context with IDDs

---

dsl_parser/functions.py
dsl_parser/tests/test_get_attribute.py

Now, you can do `{get_attribute: [n1, node_instance_index]}` in your blueprints (similar to node_instance_id).
Before, the index was only available python-side, as ctx.instance.index

RD-6445 Add `get_attribute: node_instance_index`

---

cloudify_rest_client/secrets_providers.py

Funnily, the `:` was valid syntax, because it was then a... type declaration?

SecretProviders create: fixup connection_parameters syntax

---

cloudify/plugins/lifecycle.py
cloudify/plugins/workflows.py
cloudify/tests/resources/blueprints/test-check-status.yaml
cloudify/tests/test_builtin_workflows.py
cloudify/workflows/tasks.py
cloudify/workflows/tasks_graph.py

- optimize on store
- keep NOP tasks that aren't "really" NOPs
- make heal cope with missing status
This way, we'll drop "real" NOPs from the graph (check_drift/check_status), but we'll still keep tasks that do have success/failure handlers

RD-6226 Optimize all tasks graphs when storing them

---

cloudify_rest_client/agents.py

I don't really see a reason to have this default filter. The original ticket didn't mention it.
Possibly back then we were creating many failed agents? But now, it's more stable, so let's just list all of them.

RD-6537 client.agents.list(): include all agents

---

dsl_parser/functions.py
dsl_parser/models.py
dsl_parser/parser.py
dsl_parser/tests/scaling/test_groups.py
dsl_parser/tests/test_get_environment_capability.py
dsl_parser/tests/test_get_secret.py

Compute some basic requirements for deploying blueprints, and put them into the plan:
- the names of capabilities retrieved via `get_environment_capability`
- the secrets used in this blueprint (but that can be other function calls, of course)

RD-6401 Compute blueprint requirements

---

cloudify/tests/test_builtin_workflows.py
cloudify/tests/test_context.py
cloudify/tests/test_decorators.py
cloudify/tests/test_dispatch.py
cloudify/tests/test_keep_trying_http.py
cloudify/tests/test_operation_retry.py
cloudify/tests/test_task_retry_event_context.py
cloudify/tests/test_task_subgraph.py
cloudify/tests/test_tasks_graph.py
cloudify/tests/test_utils.py
cloudify_rest_client/tests/__init__.py
dsl_parser/functions.py
dsl_parser/tests/abstract_test_parser.py
dsl_parser/tests/scaling/test_multi_instance.py
dsl_parser/tests/test_constraints.py
dsl_parser/tests/test_default_import_resolver.py
dsl_parser/tests/test_functions.py
dsl_parser/tests/test_get_secret.py
dsl_parser/tests/test_plugin_properties.py
script_runner/tests/test_script_runner.py
test-requirements.txt

If input_value is a list, under no circumstances pass it to handler.get_input. That doesn't make any sense.
It'll be just a typeerror.

RD-6597 get_input: don't break on empty data type attributes

---

dsl_parser/constraints.py
dsl_parser/tests/test_constraints.py

It seems it just works. We already evaluate them in create-dep-env.
Of course, sometimes the output of the function won't make sense for the given constraint (e.g. giving a string, rather than an umber, to max_length), but then that just has to be a runtime error...

RD-6598 Allow functions in constraint values

---

cloudify_rest_client/bytes_stream_utils.py

Just a str.split isn't enough here. This header needs to be actually parsed! Thankfully, there is a parser in the stdlib.
Before:
```bash
$ cfy plug download b4b88512-0da6-4734-80d5-9295831990f9
Downloading plugin b4b88512-0da6-4734-80d5-9295831990f9...
b4b88512-0da6-473... |################################################| 100.0%
Plugin downloaded as "plug1-1.0.0-py310-none-any.wgn", attachment;
```
After:
```bash
$ cfy plug download b4b88512-0da6-4734-80d5-9295831990f9
Downloading plugin b4b88512-0da6-4734-80d5-9295831990f9...
b4b88512-0da6-473... |################################################| 100.0%
Plugin downloaded as plug1-1.0.0-py310-none-any.wgn
```

rest-client: parse the content-disposition header

---

dsl_parser/functions.py

FunctionEvaluationError actually takes two arguments, and the first one is the function name.
Before:
```
Unable to evaluate Attribute 'x' doesn't exist in 'cap1' in deployment 'env'. function
```
After:
```
Unable to evaluate get_capability function: Attribute 'x' doesn't exist in 'cap1' in deployment 'env'.
```

RD-6477 get_nested_capability_value: correct error message format

---

cloudify/plugins/lifecycle.py
cloudify/plugins/workflows.py

When rolling back after a failed scale, only run the operations that are actually needed to roll back.
For example, if an instance failed creating, we don't need to `stop` it, only `delete`.

RD-6652 Scale: don't run unnecessary operations

---

cloudify/dispatch.py
cloudify/logs.py
cloudify/workflows/workflow_context.py

We note that there's a few layers, but at the end, the only difference between the regular WorkflowContext and a SystemWideWorkflowContext is that one sends logs with `blueprint_id: ctx.blueprint.id`, and the other with `blueprint_id: None` (and deployment_id).
Alas, `ctx.blueprint.id` is already None for system-wide executions. So they are exactly the same, so we can simplify this.

Cleanup: drop CloudifySystemWideWorkflowContext

---

cloudify/context.py
cloudify/tests/test_context.py

This is the case of manager and mgmtworker using the same directory to store resources (probably /opt/manager/resources).

RD-6614 Don't sync deployment workdir if not required

---

cloudify/context.py
cloudify/endpoint.py
cloudify/tests/test_context.py
cloudify/utils.py
cloudify_rest_client/_datetime_compat.py
cloudify_rest_client/resources.py
cloudify_rest_client/tests/test_resources.py
jenkins/Jenkinsfile
jenkins/build-pod.yaml
test-requirements.txt

We still need to support 3.6, because some plugins are still 3.6-only

RD-6744 Bring back python 3.6 CI

---

cloudify/tests/test_builtin_workflows.py
cloudify/tests/test_tasks_graph.py
cloudify/workflows/tasks.py
cloudify/workflows/tasks_graph.py

When a task has a dependency that failed, make sure to NOT run it, even if other dependencies succeed.

RD-6930 Don't run tasks with failed dependencies

---

cloudify/tests/test_local_workflows.py
cloudify/workflows/tasks.py
dsl_parser/constants.py
dsl_parser/elements/operation.py
dsl_parser/tests/namespace/test_node_templates.py
dsl_parser/tests/test_parser_api.py
script_runner/tasks.py
script_runner/tests/blueprint/blueprint.yaml
script_runner/tests/test_script_runner.py

- not only specialcase `implementation: script/path.py`, but also a script written right there
- set those operations to executor=auto, which means it'll be either host_agent, or CDA, depending on whether it is contained_in a Compute or not

RD-6846 Allow explicit scripts in script_runner

---

cloudify_rest_client/resources.py

This kind of concurrent access is not available on windows. We just get a PermissionDenied error there.
Instead, store the file, close the filedesc, then extract it, and finally remove it.

RND-205 resources client: store archive before reading from it

---

cloudify/utils.py

It used to be that the host/port were taken from the context, and envvars were a fallback.
With this, host/port are taken from the context, but if the envvars are set, they are _forced_, and override the context values.
This allows some mgmtworkers to be explicitly told, "always connect to this restservice".
This doesn't affect 7.0 agents, because they (no longer) include those envvars in their config files.

RND-297 utils: reverse get_rest_host/port sources

---

cloudify_rest_client/client.py
cloudify_rest_client/resources.py
cloudify_rest_client/utils.py

A shorthand for getting a single file. Pretty much exposes a `requests.get`, but with the credentials already in place.
Also use this method in other calls.
Also move StreamedResponse to utils so I can import it easily for typehints.

RND-347 add client.resources.get_file

---

cloudify_rest_client/summary.py

Subfield is optional, and can be None: this goes into the querystring so it needs to be omitted entirely, otherwise we do send the value as the string "none" otherwise

RND-390 Summary restclient: omit None subfield

---

dsl_parser/elements/imports.py
dsl_parser/import_resolver/abstract_import_resolver.py
dsl_parser/tests/test_plugin_properties.py
dsl_parser/utils.py

The main idea here is that we add a `resource:` scheme (next to `file:`), which will mean that the resource will have to be downloaded from the manager (i.e. from the fileserver, using essentially ctx.get_resource).
But, that means we might need to try and resolve multiple targets - one for each candidate dsl version, so `_get_resource_location` will be a generator now.
To do this sanely, there's a TON of refactors around that file, including replacing the recursive `_build_ordered_imports` with an iterative (BFS) approach.

RND-430 dsl_parser: download resources from the fileserver

---

cloudify_rest_client/events.py

These are created in snapshot_create system workflow (similarly to the manner directories are created for other entities)

RND-364 Don't makedirs for dumping events

---

cloudify/workflows/workflow_context.py

Some workflows, like upload_blueprint, should never fetch nodes. Well, there's no deployment set, so it'd fetch... all nodes in the tenant. Useless.

RND-603 workflows: don't fetch nodes when no deployment is set

---

test-requirements.txt

Version urllib3-2.0.2 attempts to include `appengine` (which fails)

Pin urllib3 in tests

---

cloudify_rest_client/deployments.py

In order to follow the progress of deleting the deployments, it'll be useful to receive the execution group id

RND-623 Delete dep-group with deployments: return excgroup id

---

cloudify_rest_client/deployments.py

Recursive means that all services contained in the given deployments (i.e. in the given environments) will be deleted as well.

RND-623 Add "recursive" for deleting deployments & groups

---

cloudify/plugins/workflows.py

With this flag, before uninstalling the target deployment, first uninstall all deployments that are using it as an environment.

RND-622 uninstall workflow: uninstall service deployments recursively

---

cloudify/context.py
cloudify/endpoint.py
cloudify_rest_client/nodes.py
dsl_parser/functions.py

Sometimes when evaluating nodes, we need to know what _instance_ we're working with.
This is the case when node properties contain functions that can only be evaluated on a node, e.g. if properties contained a `{get_attribute: [node, attr]}`, and `attr` was only a runtime property. Then, `get_attribute` tries
to fetch that from runtime properties, but to do that, it needs to know which instance to fetch from.
Sometimes it's obvious, e.g. when there's only one instance, but in case of scaling, we do get the "cannot resolve instance unambiguously" error.
However, we usually already know what instance we want, so we can just pass the id through as a hint.

RD-7086 evaluate nodes: provide an instance id hint

---

dsl_parser/elements/operation.py
dsl_parser/tests/test_parser_api.py

The old approach was clever, but still resulted in false positives: plugin names in blueprints don't actually have to be python identifiers, so a plugin path like `a-b.c.d.e` ended up being treated as a script, which is invalid.
I'll just give up, and only leave in the line count approach. Now a single-line script is disallowed, but that wasn't a very important angle anyway.

Simplify the inline script heuristic

---

cloudify_rest_client/agents.py
cloudify_rest_client/blueprints.py
cloudify_rest_client/deployment_updates.py
cloudify_rest_client/deployments.py
cloudify_rest_client/events.py
cloudify_rest_client/execution_schedules.py
cloudify_rest_client/executions.py
cloudify_rest_client/filters.py
cloudify_rest_client/inter_deployment_dependencies.py
cloudify_rest_client/node_instances.py
cloudify_rest_client/nodes.py
cloudify_rest_client/operations.py
cloudify_rest_client/permissions.py
cloudify_rest_client/plugins.py
cloudify_rest_client/plugins_update.py
cloudify_rest_client/secrets_providers.py
cloudify_rest_client/sites.py
cloudify_rest_client/tenants.py
cloudify_rest_client/user_groups.py
cloudify_rest_client/users.py

Make it possible to dump only specific entities, selected by additional iterable parameter (e.g. `agent_ids` in case of `AgentsClient` etc.) to `dump()` functions.
And also add function docstrings.

RND-309 Extend rest client's `dump()` methods

---

cloudify/plugins/workflows.py

If this workflow is called multiple times from a custom workflow, the created graphs need to have unique prefixes, otherwise they won't run

RND-561 scale workflow: add a unique prefix to graph names

---

dsl_parser/tasks.py

Nodes can have 0 instances, in which case this would otherwise throw a KeyError.
Anyway, when there's no instances, there's no IDDs (yet) to speak of.

CYBl-2049 _format_idds: don't break on nodes with 0 instances

---

cloudify/plugin_installer.py
cloudify/tests/test_utils.py

- examine available python versions
- when selecting a plugin to download, grab the one with the highest package version, and supporting the newest python version
- if no python version available is supported, default to the current version, and attempt installation anyway
- similarly, attempt installation even if the OS doesn't quite match. The "build host OS" is advisory anyway, not a strict requirement. (or, should be)
To do this, rewrite the PATH examination, to look at what python versions we have available - by checking `python --version`, not by filename. Then, switch the sorting of plugins a bit, to also include "maybe unsupported" plugins (but sorted lower than "supported")

RND-928 select plugin supporting the newest python version

---

cloudify/plugin_installer.py
dsl_parser/parser.py

Trying to max() an empty list is just going to be a ValueError. Return None instead.

RND-1207 plugin installer: return None when no plugin found

---

dsl_parser/functions.py

This ports #1296 to 7.0.2
* RND-882 Fix get_attribute for accessing dependency nodes
* Factor-out GetAttribute._resolve_node_instance for better readibility
* Fixing a fix (a.k.a. good to have unittests)

RND-882 Fix get_attribute for accessing dependency nodes 

---

cloudify/snapshots.py

Because we are running more often in a distributed environment, and /run/cloudify is a common place to keep the "work" files.

CYBL-2097 Update snapshot_restoring flag file path

---

cloudify_rest_client/utils.py

The method is used to make sure we are retrieving ALL entities when creating snapshots (in `.dump()` methods).  The fix is to use the pagination parameters correctly.
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-common/pull/1306

CYBL-2097 Fix get_all() method to retrieve ALL entities

---

cloudify_rest_client/bytes_stream_utils.py
cloudify_rest_client/executions.py

* Provide more information in OSError at writing a stream response to a file
* Just log RuntimeErrors as well as CloudifyClientErrors when restoring execution groups from a snapshot
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-common/pull/1311

CYBL-2097 Snapshot restore fixups

---

cloudify_rest_client/log_bundles.py

The method is used by mgmtworker's log-bundle create workflow to upload a created archive.  The manager (which receives the file) in this case acts as kind of proxy for a file server service (e.g. SeaweedFS, local storage).

NE-7793 Implement LogBundlesClient.upload_archive

---

cloudify_rest_client/executions.py

Executions which were still running (i.e. had one of the statuses: `pending`, `started`, `cancelling`, `force_cancelling` or `kill_cancelling`) when the snapshot was made, will be marked as `cancelled` and information about that modification will be save in the `error` column of the execution.  It means a manual examination may be required to determine their state.

NE-19591 Mark not-complete executions as cancelled

---

cloudify/cluster.py
cloudify_rest_client/client.py

Retry mostly all failed requests, and do the retries with a delay.
This backports NE-17825 to Cloudify

NE-17922 cluster client: retry more requests

---

cloudify/dispatch.py

.partition can't be called without arguments. Use .split and a check

cloudify.dispatch: fix _update_logging_level
